#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const PACKAGE_PATH = path.dirname(require.resolve(path.join('china-dictatorship', 'package.json')));
console.log(fs.readFileSync(path.join(PACKAGE_PATH, 'README.html')), 'utf8');
