= FAQ
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

toc::[]

== Why are you attacking websites with censored keywords?

<<keyword-attack, The attack>>.

To <<effective,destroy the firewall>>.

This would then end censorship.

And then <<dictator-needs-gfw,I believe>> that this would also <<why-end-dictatorship,end the dictatorship>>.

The keyword attacks increase the cost of censorship.

If commies censor things, they will get worse IT technology, and thus become less rich and militarily powerful.

Maybe this hurts my argument, but Hillary agrees: https://youtu.be/d3dE_LDz_9E?t=1681 :-)

Since all they care about, like any other politicians, is power, the only way to make them stop censorship is to make the cost of censorship higher than not censoring.

Without the threat that China will be less technologically, and therefore militarily advanced, there is no incentive for the CCP to destroy the firewall.

The goal is to put them in a position where they have to choose between either:

* having military power
* remaining a <<dictatorship,dictatorship>>

but not both, since having both means that they will <<war,start WW3 and destroy humanity>>

[[harm-programmers]]
=== Do you want to harm the Chinese programmers?

No.

This is not a revenge of any kind.

I know I am harming you on the short term, and I don't like myself for it.

But I believe that this harm is a necessary means to reach my real goal, which is to destroy the firewall, and the dictatorship.

Don't you think it is worth a try? Destroying the firewall, would <<why-end-dictatorship,enormously benefit>> not only Chinese programmers, but every single other Chinese person too.

Once the firewall is destroyed, which <<dictator-needs-gfw,may destroy the dictatorship>>, I want China to develop the best science and technology in the world, and <<would-you-like-to-live-in-china>>.

And by the way, by contributing to open source, I am already helping China, and all underdeveloped countries become stronger.

[[why-end-dictatorship]]
== Why do you want to end the dictatorship?

Because I think that this would make China, and the world:

* <<richer,richer>>
* less likely to get into <<war,WW3>>

[[richer]]
=== Why would democracy and freedom of speech make China richer?

There is infinite debate about this out there, some examples:

* http://www.becker-posner-blog.com/2011/05/can-poor-countries-afford-democracy-becker.html
* https://www.quora.com/Is-democracy-or-authoritarianism-better-for-developing-countries

For:

* dictatorships are more likely to start <<war>> or other crazy policies like the Great Leap Forward, which completely destroy the economy in one go
* society becomes richer when people know that they can do their startups, get rich, and stay in the country without fear of being persecuted unfairly and losing everything instead of migrating to Canada.
+
Any criticism of the government, even if constructive, is taken as menace to power, and more likely to be shut down, which makes the government and just becomes less efficient since there is less feedback.
* governments are monopolies, and the more powerful they are, the worst it is for competition an efficiency in general. E.g.: the startup with better government ties wins, instead of the most efficient one.

Against:

* presidents only care about the 4-8 year horizon, while dictators can make longer term decisions to maintain power forever, their power being limited only by "the people are happy enough to not start a revolution"
* dictatorships can make changes faster without the same amount of discussion that happens in democracies, where power is more spread out.
+
Killing a million people will make us richer? No problem, let's do it.
+
That is great when they make good decisions, but it sucks when they make <<war,bad ones>> more likely.

I really like Posners' way of putting it:

____
While average rate of growth do not appear to differ much between democracies and authoritarian regimes, the variability in performance does differ more among authoritarian governments. China has had remarkable growth since the 1980s, but the prolonged devastation and hardship produced by China’s “great leap forward” (when millions of farmers starved to death) and its Cultural Revolution would unlikely have occurred in a democratic country like say India. Nor is it likely that say Cuba and many African nations would have suffered so long with such terrible economic policies if they had reasonably democratic institutions.
____

Maybe China was poor because of Mao's crazy communist regime. Similar regimes also made Russia poor. And yes, before that exploitation by the West may have been a factor.

Definitely, the current regime is better than Mao's, but just imagine how rich China could be if it had more freedom and justice.

Imperial China lost the race for the Industrial Revolution. Will another dictatorship be able to stay on top of the next technological revolution?

[[war]]
=== Why would democracy and freedom of speech make China less likely to start a war?

This has been discussed to death:

* https://en.wikipedia.org/wiki/Democratic_peace_theory
* https://en.wikipedia.org/wiki/Perpetual_Peace:_A_Philosophical_Sketch

Some arguments include:

* the people who will actually fight and die on the front can't vote against it
* dictators have huge power, so if they put it in their heads that they want to start a war, it is much harder for sensible people to stop them
* dictators need <<fear-of-west,to keep the people in fear all the time to keep their power>>, and a war is a great way to achieve that

[[fear-of-west]]
=== The commies exaggerate the thread of the West to keep in power

This is a common strategy, but the West is not as evil as they say:

_____
Once upon a time, there was a farmer with a farm.

One day, the animals in the farm started feeling a bit trapped, and started bumping against the fence to get out.

The farmer, however, was smart, and told the animals:

____
> Careful! There is a wolf outside! If you go out, you will be eaten by the wolf!
____

The animals, were not that smart, and listened to the farmer, they were afraid!

From time to time, one of the animals would disappear (and without their knowledge, reappear on the farmer's dinner table).

But the farmer kept giving the animals delicious food without them doing any effort, so they decided to believe the farmer's explanation that that animal had escaped and been eaten by the wolf.

Maybe, there was actually a wolf outside. But if they had escaped, only some of the animals would have been eaten by that wolf.

But by staying in the farm, all the animals were, sooner or later, eaten one by one.
_____

TODO source.

==== Censorship is necessary to protect China from harmful USA propaganda

I don't think this is below them, but:

* without censorship, you would be much richer and stronger, and more able to defend yourselves
* why does China also censor its own people in addition to foreign propaganda?
* maybe this fear is greatly emphasised by the Chinese government beyond truth just to help them keep control of the country by fear and maintain their own power. Can the Americans really have that much influence in your country?
* maybe the regions that want to split from China feel like China is not giving them anything back, and they are themselves looking for allies outside of China to help them split. With democracy, people are more likely to get what they want, and there will be split parties and votes.
* the same argument can be used to justify any action, no matter how bad. E.g.: we must put all who criticize the government in jail, or else they will make China less united and weaker against the USA!

=== The Chinese masses are still uneducated, and not fit for free speech and democracy

When will they be ready? Who decides? What if they think that they are ready now?

[[effective]]
== Will the keyword attacks really help to destroy the firewall?

=== Embargoes make the dictatorship stronger

The <<keyword-attack,keyword attack>> is basically an embargo.

There is already a lot of literature about this, specially in the cases of Cuba and North Korea. It is basically a libertarian vs conservative / Cato vs Heritage thing in the US:

* https://www.cato.org/publications/commentary/no-embargo-harms-cubans-gives-castro-excuse-policy-failures-regime
* https://www.heritage.org/trade/report/why-the-cuban-trade-embargo-should-be-maintained
* http://www.slate.com/articles/news_and_politics/the_big_idea/2006/08/thanks_for_the_sanctions.html

Some ideas:

* This embargo is a bit different than other in the following sense:
* Programmers are more likely to develop better Firewall climbing tools if SO is blocked
* If we don't take any action to show our dissatisfaction, the dictatorship never ends.
+
The commies exist like any other organization for a sole purpose: maintain their own power.
+
If nothing is done to show dissatisfaction, they will never give up on that power.
+
There are two extremes of action (both which _I don't_ support):
+
* everyone become a willing mindless slave of the leader: perfect stability
* everyone take up arms and do terrorism: perfect instability
+
But between those two extremes, what is the right measure? I think that saying nothing is too close to stability.
+
I do see that one alternative scenario is that if we do nothing, maybe there will be more and more contact with Western countries, and the Chinese will see for themselves that we are not that bad, and eventually request democracy.
* Even if programmers get very powerful, it is not very likely that they will succeed to undo the dictatorship, they simply don't have enough power.
+
I'd rather have a less strong dictatorship, than one with good programmers.

==== Keyword attacks could be used by certain CCP political groups to justify blocking off the entire external Internet, and make the dictatorship even more pervasive

It is a risk, but it would make China drastically <<richer,less powerful>>, so at least they wouldn't be able to start or sustain <<war,WW3>>. So I don't think it will go that way.

=== What you are doing will never have any effect

That is true with high probability, just like any other individual which tries to influence 1B people.

Every action is statistical: I just push the balance a little bit towards freedom.

This FAQ and any talk is useless. You and I are wasting our times here.

The possibility of blocking Stack Overflow and GitHub is 1000x more useful than any talk, but it is still useless.

However, potentially blocking those websites takes <<better-to-do,0 of my time>>, I just leave the content there, so it is worth my time.

To have an idea, in 2015 there are about:

* 20M developers in the world
* 2M in China : https://www.quora.com/Approximately-how-many-programmers-are-there-in-the-world http://www.techrepublic.com/blog/european-technology/there-are-185-million-software-developers-in-the-world-but-which-country-has-the-most/
* 5M Stack Overflow users http://data.stackexchange.com/stackoverflow/query/227868/select-count-from-users
* TODO I wonder what percentage of GDP those programmers control. I'll bet any programmer on Stack Overflow is at least 5x more powerful than the average Chinese.

And if we never start somewhere, nothing will ever happen.

=== Stack Overflow could be blocked at no cost by the Chinese government

Hitting the block button has of course no cost.

The cost of blocking Stack Overflow lies of course in the loss of information, and slower technological development.

[[dictator-needs-gfw]]
== Would ending the great firewall truly end the dictatorship?

Not 100% sure.

In Russia for example, the Internet is relatively free, but the government controls most professional media, which is what most people end up seeing, by suing dissidents media out of business.

But on the other hand Russia is already much freer than China.

Although I don't like them, I can't deny one thing: the commies are smart, and when they do something (e.g. censorship), it tends to keep them in power.

== This is your personal problem, we have nothing to do with it, stop punishing us for it

We have to fight for justice for our fellows, or else when injustice happens to us, no one will fight for use either.

Every form of protest incurs some damage. E.g., if we manifest on the street, it generates a traffic jam.

I don't like it, but I think it is worth it.

How can you be that certain that your children won't have dissident ideas and be punished unfairly for them?

Intolerance is a risky way to live.

If you just work to make money and have a good life, without any plans to improve the government, you are just making the economy of the dictatorship stronger, then when they start a <<war,war>> or kill yet another minority, blood will also be on your hands.

== If anyone disagrees with the government they must be punished to keep the stability of the country

Destroying diversity is the best way to reach a point where everyone can agree to start a new big war and destroy everything.

The CCP thrives on the excessive fear it instigate into its own people.

How can society improve, if we are never allowed to try new things out?

Change does not require violence. Violence happens because the government punishes any dissidence, even if pacific, to retain its own power.

In democracies, radical policy changes happen without dropping a single drop of blood.

== You are using Stack Overflow in a way that it was not meant to be used, so what you are doing is in principle wrong

Any act of protest will use things in ways that it was not meant to be used.

For example, the street is not meant to showcase protest banners, it is meant to be a passageway for cars.

Making a statement where no one will ever see it, like a personal website, is <<effective,sure to have no effect>>.

Finally, it is up to the Stack Overflow community to decide what is right or wrong, and so far the consensus is go ahead:

* http://meta.stackoverflow.com/questions/298950/are-political-profiles-that-could-possibly-affect-the-participations-of-other-us
* http://meta.stackoverflow.com/questions/267368/are-political-avatars-and-profiles-ok
* http://meta.stackoverflow.com/questions/299882/can-a-username-be-considered-spam
* http://meta.stackexchange.com/questions/286082/does-the-be-nice-policy-require-se-users-to-be-nice-to-people-who-are-not-se-u/286090#286090, see public figure comments

Much of the best art and technology is about using something in a way that it wasn't meant to be used.

=== Are you making programming contributions with the main intent of promoting your policital agenda?

No, that is just a side effect.

If that were the case, I would definitely target more widely technologies, in particular Web and JavaScript, instead of obscure things like C and assembly in which I have spent tons of my time.

Also, as I've said elsewhere, my actions are very unlikely to have any actions. Much more likely to have any action, would be for me to become rich and powerful first, and the best way to do that is to invest in whatever I think is most useful.

Actually, it can even be argued that I'm somewhat irrational, since I would much more likely become rich and powerful by bowing down to the CCP and trying to get their money instead.

On the other hand, becoming rich and powerful is also highly unlikely, so maybe I'm just taking a low risk low reward path?

I have very little free time, and will never do something for political resaons, only things that interst me technically.

Finally, do you really think I'd be able to make such awesome projects if I had primarily politicial considerations in mind? XD

==== Are you making trivial edits on questions just to spam your name further?

No.

I just think that website is great, and want to push it to perfection, in particular with better Google keyword hits, and uniform gramatically correct titles.

If you think that any of my edits were harmful, please ping me and open a meta thread to discuss specific edits, and I will comply with consensus.

== You are not Chinese, you can't interfere in Chinese politics

. We live in the same world.
+
If China's <<richer,economy>> is bad, my economy is worse.
+
If China's environment is bad, my environment is worse.
+
If China <<war,starts a war>>, I might have to fight it.
. If I lived under a dictatorship, I would welcome foreign intervention.
+
Even if you don't, I know several Chinese who do.
. You have been brainwashed by the commies who say that all foreigners are bad :-)
+
The commies do this because most foreign countries are telling the Chinese to get rid of the dictatorship.
+
Most foreigners actually want what is best for China.
. You can't do anything about it.
+
I don't like this argument, but in the end, this is what all politics comes down to: power.
+
I recognize that in that sense, I may be similar to the CCP and any other political party.

=== You are not Chinese, you have been brainwashed by the USA know nothing about China

Everyone is "brainwashed" by their environment.

I don't doubt that you know more about China than me.

So, instead of saying that, why don't you just actually prove your point by teaching me something interesting about China that I don't know about? I love learning new things.

But if you are Chinese, also consider that you have been brainwashed by the commies, and likely more than me since you live in a dictatorship.

=== Have you ever lived in China?

No, only visited once.

And I don't think it is a good idea for me to do that now :-)

==== Would you like to live in China?

If the dictatorship ends, I would like to <<do-you-hate-china,migrate to China>> if given a decent job to help you develop and become awesomer.

=== What is your Chinese level?

Oral enough for daily things, but not understand a natural casual dinner conversation.

If it matters, with some patience, I can make myself understood though.

I read with link:http://www.perapera.org/[Perapera], write with a mixture of link:https://www.pleco.com/[Pleco], Google translate and Googling to see if Chinese actually say the sentences that way.

I haven't tried to learn characters, too much effort, but I learnt the most common ones without trying.

I really wish I could learn more, but I have other more important endeavours at the moment :-(

== This repository is completely biased against the Chinese Government!

I prefer the term focused :-)

That being said, I take the agenda of information sources very seriously.

E.g. I try to clearly classify Communist Party, Falun Gong, and Western government linked sources.

== China is fine as it is, stop making it worse

Welcome to the wonderful world of democracy, a world where people can have different political opinions than you! :-)

I try to justify here why I think China would be better with democracy, but I know that ultimately all of this is useless, our opinions are all determined genetically and by bringup, and there is nothing I can do to change yours, or you change mine.

Part of my philosophy however is to accept your opinion without becoming mad, even if it is contrary to mine, and therefore wrong.

== Irrelevant personal questions

=== Why did you start the keyword attack?

The last straw was when in March 2015 my girlfriend's mother was arbitrarily kept 15 days in jail for doing Falun Gong. I posted this at:

* https://twitter.com/cirosantilli/status/579270450984984576
* https://www.facebook.com/cirosantilli/posts/952661734753174

I then continued because I hate political censorship.

I am against violence. <<do-you-hate-china,I love China>>.

==== Jail post en

My girlfriend's mother, a 63 year old lady, was kept 15 days inside a Chinese "correctional facility" because she does Falun Gong.

She had to stay all the time in a small room with a bed and a toilet, under video surveillance, being fed three meager meals a day.

I see Falun Gong http://en.wikipedia.org/wiki/Falun_Gong as just another moderate religion which causes no harm to its believers. The only reason that it is unofficially outlawed in China is because the communists fear it as a political competitor.

There was no trial and no explanation. She was going to take a train to visit her sister. But she didn't know that there was an important political event happening in the capital: http://en.wikipedia.org/wiki/12th_National_People's_Congress So the police at the station, who already knew she did Falun Gong, took her away.

When she came back home, the house had been searched and was all messed up. Her religious books and computer were missing.

I'm glad she was not physically harmed. I find it fascinating how even well educated Chinese support a government which simply does not represent some of its people. How will you feel when something like that happens to your own family, and there is nothing you can do about it?

==== Jail post zh

(Translation by my wife)

我女朋友的母亲，一位63岁的女士被监禁在一个中国的“劳教所”，只因为她炼法轮功。

她被迫待在一个小屋子里面，只有一张床和一个排泄的地方，一直处在监视器下，每天两个窝头一碗只有几个白菜叶的汤。

我看过法轮功http://en.wikipedia.org/wiki/Falun_Gong 只是一个和平的信仰，对相信它的人没有任何坏处。它在中国被非官方的定为违法（其实没有一项明确法律禁止），唯一的原因就是工产党害怕它是一个政治竞争对手。

没有审讯没有任何解释。她正准备坐火车去看她的姐姐。但是她并不知道那个时候有重要的政治会议正在首都进行：http://en.wikipedia.org/wiki/12th_National_People's_Congress
所以那些知道她炼法轮功的铁路警察把她带走了。

当她回到家中时，房子被搜查过了，四处一切混乱。她的信仰书籍和电脑都没有了。

我很庆幸的是她身体并没有受到伤害。我觉得很意思的是一些受过良好教育的中国人怎么能够迫害一部分它的人民的政府呢？如果这样的事情发生在你的家庭，而你什么都不能做，你会怎么想？

==== Jail post pt

A mãe da minha namorada ficou 15 dias num "centro de correção" chines porque ela faz Falun Gong.

Ela ficou o tempo todo num quarto pequeno com uma cama e banheiro, sobe videovigilância, recebendo 3 refeições pequenas por dia.

Para mim, o Falun Gong http://en.wikipedia.org/wiki/Falun_Gong é apenas mais uma religião moderada que não causa nenhum problema para seus crentes. A única razão pela qual ele é proibido na China é porque os comunistas tem medo dele como competidor politico.

Não houve julgamento nem explicação. Ela ia pegar um trem para ver sua irmã, mas ela não sabia que teria um evento político importante na capital: http://en.wikipedia.org/wiki/12th_National_People's_Congress Então a polícia da estação, que já sabia que ela faz Falun Gong pegou ela.

Quando ela voltou pra casa, a casa tinha sido procurada pela polícia e estava uma bagunça. Os livros religiosos e seu computador foram confiscados.

Eu fico feliz apenas que ela não sofreu abuso físico. Eu acho fascinante como mesmo muitos chineses educados apoiam ainda um governo que não representa parte do povo. Como você vai se sentir quando algo do tipo acontecerá com a sua família, e você não pode fazer nada sobre isso?

=== Are you a radical?

Radical: I don't consider myself a radical because I actually have doubts about doing this sometimes.

I never get mad. Only a slightly sad or annoyed sometimes.

But I do admit that I am hard headed like almost all humans, and it is very unlikely that anything anyone says will change my mind about subjective political matters.

In the end I just end up thinking about new replies to those arguments and adding them to this FAQ.

But maybe no radical ever considers himself radical? Hmmm...

link:https://www.youtube.com/watch?v=efHCdKb5UWc[The Dark Knight - Some Men Just Want To Watch The World Burn]. I worry sometimes.

=== Do you think Chinese politician X evil?

The term evil does not make sense to me.

The best definition I can reach is a psychopath with zero empathy for anyone: https://en.wikipedia.org/wiki/Psychopathy although I think that can be better characterized as a disease or extreme personality trait.

I believe that the huge majority of those politicians are just regular dudes with a knack for politics but brought up in a fucked up political situation.

Just like you, me and other politicians in any country.

=== Do you think the Chinese government is evil?

No, just <<richer,inefficient>> and <<war,dangerous>>.

To me, it's just another non-democratic empire like the Qing Dynasty. 共产朝 as I call them. But alas, I'm not the inventor of the expression: http://web.archive.org/web/20161025220242/http://tieba.baidu.com/p/752094668

=== Are you a SJW?

SJW: there is a seed of SJW in me.

One major difference between me and the stereotypical SJW is that I never engage in lengthy discussions.

I believe that you cannot change people's mind's, and that learning tech is more worthy of my time.

I limit myself to listening as much as I can to learn new arguments.

So the rationale of my actions is _not_ to convince anyone, but rather:

* increase the monetary cost of censorship by binding politics to tech
* group up like minded people who don't like censorship

=== Do you hate China?

On the contrary. China has my favorite food, language, history, culture and nature in the world. And because of that: <<would-you-like-to-live-in-china>>.

As link:https://en.wikipedia.org/wiki/Bjarne_Stroustrup[Bjarne] said:

____
There are only two kinds of programming languages: those people always bitch about and those nobody uses
____

I only focus here on negative things to provide content that will activate the Great Firewall.

==== Why do you love China so much?

I don't believe in reincarnation, but sometimes I'm tempted to.

Interesting how different people get <<do-you-hate-china,different impressions>>!

=== Are you doing this because it makes you feel important?

No, I am a selfless human being, only concerned with the well being of humankind.

=== Would you be doing this if you were in China?

Not with my real name attached to it.

=== Do you believe in or practice Falun Gong?

No, I'm agnostic: https://en.wikipedia.org/wiki/Agnosticism

=== There are bad things happening all over the world, why don't you fight for those causes as well / instead?

We have to choose the one we think is the worst, and focus on it.

What is worse is a subjective choice. For me:

* I love China and my Chinese wife
* I hate dictatorships, and China is the largest one

My <<keyword-attack,SO username>> and protest time are not infinite.

== Is your campaign funded or otherwise supported by some organization?

Nope.

But then, a shady supporting organization might require that I don't disclose their support, so maybe the best answer is that you will never know for sure.

Of course, a hidden support would represent a reputation hit for both such organization and for me, which makes it less likely that I would have accepted or had such an offer.

Also consider my motivation. If your mother in law were put into jail unfairly for 15 days, for following the same religion that your wife follows, and if you had a social media presence, wouldn't you be tempted to do the same?

What about you, are you funded by the CCP?

See also: https://github.com/cirosantilli/china-dictatorship/blob/48a95bf57a16b85619a6ae68702d18c9a5078797/FAQ.md#flg-has-been-funded-by-the-us-government-at-least-once-therefore-it-is-evil

=== Does your employer support this?

My employer has nothing to do with this.

He doesn't approve or disapprove of the Chinese government or of my private actions.

The only thing that my employer _does_ believe in is that employees can have their own political opinions, and that this should not affect hiring decisions.

Obviously, this action limits my ability to lead high profile deals with China.

Also I'm quite curious if this would limit my ability to go to China for business, but I haven't applied for a visa since I've started this. It likely wouldn't be a good idea for me to go to China :-)

But my employer believes that inclusion and non-discrimination is more valuable.

I will always do my best to not let my personal opinions affect my professional decisions, as that would be unfair to my employer.

[[better-to-do]]
=== Don't you have anything better to do?

In 1989, a beautiful thing called the World Wide Web was invented.

The Internet gives everyone the magic power of writing something, and having million people read it for free!

This is how much time I spend on this to give you an idea:

* every week or two, someone sends me a message, I reply with "read the FAQ", and usually update 
* I follow https://www.reddit.com/r/China amongst many other programming subs, and all major bad news show up there
* when something bad enough comes up, I go to https://chinadigitaltimes.net/china/sensitive-words-series/ and update <<keyword-attack,my keyword attack>>. I've only been updating it on Stack Overflow these days, since GitHub does not show my profile name prominently.

Then I just contribute to programming websites exactly as I would if I weren't making this campaign.

== Were you influenced by the Cute cat theory of digital activism?

https://en.wikipedia.org/wiki/Cute_cat_theory_of_digital_activism

Nope, someone told me about it after a while, but it is basically what I'm doing.

You can never invent anything new anymore nowadays.

== People in China have already considered democracy, and rejected it

OK, shall we put that to an anonymous vote just to make sure?

Dear sir or madam: do you want more control over your government? y/n

== Are for a violent revolution to overthrow the CCP?

No, I'm against physical violence.

And furthermore it would never work, since the CCP controls the army.

I propose instead a revolution of ideas, and efficient link:https://en.wikipedia.org/wiki/Nonviolent_resistance[nonviolent resistance].

Where efficient means: if you are a dissident, use privacy technology, and weight well the benefit vs risks of your actions.

You are often more useful to the cause outside of jail than inside.

[[dictatorship]]
== Why do you say China is a dictatorship?

True, I'm using the word in an extended / jokingly sense.

Maybe authoritarian is a more precise term.

In particular, dictatorships are harder to sustain than authoritarianism, since it generally implies even less freedom.

Dictatorship is becoming link:https://www.nytimes.com/2018/03/07/world/asia/china-xi-jinping-party-term-limit.html[more and more precise under Xi] however.

[[keyword-attack]]
== What is a screen name keyword attack?

Adding censored words to your username: https://stackoverflow.com/users/895245

This only works on websites that show usernames everywhere.

This then leads to your username appearing on thousands of pages, depending on how much you contribute to the website.

It is also possible to do it with with images, although this is less effective in taking down websites since images are harder to track automatically.

This type of attack is essentially an embargo.

=== Do Stack Overflow policies allow for keyword attacks?

The current consensus is yes:

* https://meta.stackexchange.com/questions/286082/does-the-be-nice-policy-require-se-users-to-be-nice-to-people-who-are-not-se-u
* https://meta.stackoverflow.com/questions/267368/are-political-avatars-and-profiles-ok
* https://meta.stackoverflow.com/questions/299882/can-a-username-be-considered-spam
* https://meta.stackoverflow.com/questions/299882/can-a-username-be-considered-spam
* https://meta.stackoverflow.com/questions/349131/users-political-display-name-triggering-government-action-against-users-who-vie

The Chinese law doesn't I'm afraid :-( https://advox.globalvoices.org/2015/04/16/new-internet-rules-in-china-target-usernames-avatars-as-subversive-tools/

=== What are the best sources of anti-commie news?

https://www.reddit.com/r/China

Catches all the important news

A large part of the posts is controversion material.

Has some noise of course as well, but less than other media I find.

Highly worth your feed.

Reddit was banned in China in August 2018: https://www.reddit.com/r/China/comments/965k4c/reddit_banned_in_china/

=== Where can I find good words for a keyword attack?

* https://chinadigitaltimes.net/china/directives-from-the-ministry-of-truth/?view=all updated weekly with the newest news. TODO credibility, methodology. Chinese version of list: https://chinadigitaltimes.net/chinese/category/%E6%9C%89%E5%85%B3%E9%83%A8%E9%97%A8/%E7%9C%9F%E7%90%86%E9%83%A8%E6%8C%87%E4%BB%A4/?view=all
** A wiki of subversive claims by the same source: https://chinadigitaltimes.net/space/Main_Page, the "Grass-mud horse index" (cao3n2ma3 草泥马), with a censored term of the week section.
** Fun 2015 ebook: https://github.com/cirosantilli/decoding-chinese-internet-pdf-download
* https://en.wikipedia.org/wiki/List_of_blacklisted_keywords_in_China> <https://zh.wikipedia.org/wiki/%E4%B8%AD%E8%8F%AF%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9C%8B%E5%AF%A9%E6%9F%A5%E8%BE%AD%E5%BD%99%E5%88%97%E8%A1%A8
* https://github.com/jasonqng/chinese-keywords
* link:complete-gfw-rulebook-for-wikipedia-v3.0.pdf[]
* https://qz.com/698990/261-ways-to-refer-to-the-tiananmen-square-massacre-in-china/ 261 ways to refer to the Tiananmen Square Massacre in China

=== What makes for good censored words?

* recent cases receive a large prime over raw death toll, because older cases can always be attributed to other people.
+
E.g., I've heard there is even some opening towards acknowledging the Great Famine, thus 烏坎事件 (and others from my previous profile names)
* words must refer to a precise event, and must be clearly summarizable in very few chars, for increased impact, and profile name length limitations.
+
E.g. "High corruption rates, high pollution", although very serious, feel too generic.
* events that relate directly to freedom of speech receive a prime, since they can only happen in China and very few other countries.
+
E.g.: Falun Gong, Tiananmen.
+
Non e.g.: corruption and pollution. Those are hard to quantify, and there is always an immediate reply: china GDP per capita is low, same happens in India, Brazil, etc.
+
Freedom of speech however, is immediately verifiable (e.g. "my Weibo was taken down"), and undeniably caused by the current central government.

=== Are there other openly dissident users on Stack overflow?

* "GNUSupporter 8964民主女神 地下教會"
** https://math.stackexchange.com/users/290189/gnusupporter-8964%E6%B0%91%E4%B8%BB%E5%A5%B3%E7%A5%9E-%E5%9C%B0%E4%B8%8B%E6%95%99%E6%9C%83
** https://web.archive.org/web/20180924203410/https://math.stackexchange.com/users/290189/gnusupporter-8964%E6%B0%91%E4%B8%BB%E5%A5%B3%E7%A5%9E-%E5%9C%B0%E4%B8%8B%E6%95%99%E6%9C%83
** Keyword attack inspired by me
* Yu Hao
** http://stackoverflow.com/users/1009479/yu-hao
** http://archive.is/76FCb
** "GFW (Great Firewall of China) is one of the most notorious inventions in the history of Internet. Anyone working for it should be ashamed."
* Terry Wang
** http://stackoverflow.com/users/1801697/terry-wang
** http://archive.is/V0aSK
** Lego recreation of Tankman on profile picture.

Users who had GFW references but removed it:

* http://stackoverflow.com/users/4594532/gnimuc-key
** http://web.archive.org/web/20170331144256/https://stackoverflow.com/users/4594532/gnimuc
* http://stackoverflow.com/users/651907/jclin
** http://web.archive.org/web/20160516065151/https://stackoverflow.com/users/651907/jclin

Users who mentioned me in their profiles at some point:

* https://web.archive.org/web/20170602054631/https://stackoverflow.com/users/815408/%E8%AF%B7%E5%B0%81%E6%8E%89ciro-santilli-%E4%B8%AD%E5%9B%BD%E5%85%B1%E4%BA%A7%E5%85%9A%E4%B8%87%E5%B2%81

Query to find them: http://data.stackexchange.com/stackoverflow/query/312863/mentioned-ciro-santilli-on-aboutme-or-displayname

== What do you think about separatism?

Personally, if a large number of people in a given region want to leave an country strongly or have greater autonomy, I believe that they should be allowed to do so.

Rationale:

* if they don't feel they are getting a good deal out of your country, it is unfair to keep them in
* keeping them in the country implies large scale violation of human rights: mass incarceration and removing freedom of speech.
+
Which in turn implies terrorist backslash.
+
All of which are against my principles.

What makes me the most mad is the censorship. If you are going to put people in jail, write a clear law about it, and let international reporters come to see the situation.

== Falun Gong

=== Do you support FLG, or just use it because it is a censored?

I don't support FLG specifically, only freedom of religion.

I use it in my usernames simply because it is the most banned and censored one in China today.

I believe that individuals should only be put in jail for what they do, not for what they believe.

I consider FLG <<flg-religion,a religion like any other>>, and I am against its ban, as I am for all other religions.

Also I believe that freedom of speech and democracy imply that FLG and other religions will exist. If you want freedom, you have to accept other people's choices.

Otherwise, democracy and communism can also be considered as religions, and banned.

=== Do you support FLG just because your wife and mother-in-law do it?

Not consciously.

I think that **70 Million** people (6% of the total population in 2000!) getting completely squashed by the Party illustrates extremely well the dangers of the dictatorship.

=== In the Tweet you say "correctional facility", but reeducation through labour has been abolished

My bad https://twitter.com/cirosantilli/status/579270450984984576[here], the precise term is "jail". I'm _not_ talking about: https://en.wikipedia.org/wiki/Re-education_through_labor Unfortunately I can't edit a Tweet.

[[flg-changed]]
=== Falun Gong is completely different in the West than it was in China

I believe that it has changed.

But isn't that the case of every cultural religious movement that migrates to a completely new culture?

Main points which may have changed:

* It has become more organized.
+
But why shouldn't they organize to defend themselves now that they have the chance without being put into prison?
+
The CCP is highly organized and has way more resources.
* Less emphasis is given to the religious / mystical aspect, and more to the corporal exercises, and health aspect.
+
This may be because people in the "West" are:
** are "scientific-educated" atheists who wouldn't go for a "religion"
** already have other religions, which would view FLG as a taboo

Also maybe only the richest and most educated believers managed to escape China, and thus the movement carried that bias outside China.

If you know more ways in which it may have changed, let me know.

But once again, we can know nothing for sure about the past in China because of censorship.

Even if you saw something yourself, how can you be sure that it is representative?

And if it has changed, now that it has changed, maybe China should unban it?

=== FLG has been funded by the US government at least once, therefore it is evil

1.5M USD in 2010 for a FLG controlled internet freedom group http://news.bbc.co.uk/1/hi/world/americas/8678760.stm

But well, if you are going to do something anyways, and someone offers you money, why wouldn't you take it?

Taking the money does of course give a "bad impression" that someone is trying to buy influence, but does it in itself imply that you are doing something bad?

But do you really think that the US government paid that to buy influence in FLG? What would they force upon that FLG group that they didn't already want to do? Isn't it more likely that the US government wanted them to continue doing exactly what they were doing?

Every government funds groups it supports, it is an all out war I suppose. Compare that to the propaganda funds of the CCP.

What about the funding of political campaigns, which vastly outnumbers 1.5M USD every year?

=== FLG is illegal in China, we must follow the law

This might be a bad law that should be changed.

It was perfectly legal for Nazis to kill Jews. Does it make that right?

=== FLG is fake

The same can be argued about any other religion or political belief of type: it is better if we organize society in this or that way.

How can you disprove their belief, when as in any other religion, every affirmation made hinges on "miracles only happen around when true believers are around" or "only true believers can perceive evidence in their hearts / minds directly". He died of cancer? Not a true believer.

Conversely, do you understand the full sequence of experiments that imply quantum field theory? Have you seen videos of those experiments? Have you attended live demonstrations? Do you understand the construction of the experimentation apparatus? Yet, why do you believe it?

More importantly: what do you propose that should be done about it? Should we kill followers? Or is jail enough?

==== FLG is a very new religion and therefore fake

The Romans called Christianism the "Cult of Jesus".

If I tell a lie today, will it become true in a thousand years? Or a truth today become a lie?

Try sending an email to <<flg-lhz,LHZ>> asking him to prove his powers to you :-)

=== Many people both are against censorship and FLG

I know that, and that supporting FLG is "bad" for my public image with most Chinese, including those that are against censorship.

But without censorship, there will be democracy, and with democracy FLG followers will have voting rights, and FLG will become legal.

I think the situation is very similar to Scientology in the USA today: most people dislike it, but believe that you can believe whatever you want.

Democracy and Communism can also be considered as religions and persecuted.

Isn't it convenient when a dictatorship gets rid of those weirdos for you? But not so much when suddenly you or your family is the weirdo...

If you are not ready to accept the beliefs of others, then maybe dictatorship is better for you after all.

==== Why do you say that democracy is a religion just like FLG?

Because it also specifies irrational and fundamental aspects of how one should live, notably voting and freedom of speech.

Like the Cult of CCP has one fundamental belief: the Party is always right.

=== Many people say they do FLG only to get VISAs to the USA

Heard this a few times, and I believe it has happened.

But I don't see how this is relevant at all to this discussion:

* if they are not really FLG believers, they should be prosecuted, but this says nothing about the real FLG believers,
* if they are, then why wouldn't they seek a VISA, since they are in constant threat of going to jail or worse in China, and the USA law gives them that right?

Sample news:

* https://www.npr.org/sections/money/2018/09/28/652218318/thousands-could-be-deported-as-government-targets-asylum-mills-clients

=== I have personally seen people do bad things because of Falun Gong

Either direct suicide or <<flg-medication,dying because of not taking medication>>.

First, I'm not saying I don't believe you, and I'm sorry about what happened.

But your testimony is worthless unless you give the following:

* clear unique personal identification
+
This is because the CCP has thousands of wumaos who could make fake reports.
+
There are basically two ways to do that:
+
.  your testimony is done in video form on YouTube clearly showing your face as you make it
.  links between a notable social media presence that is hard to achieve, e.g. Twitter with many followers, Stack overflow with a lot of rep, and the account
+
Either of those must contain / link to information that uniquely identifies you. Generally, full name, city and date of birth is enough.
* a precise testimony that states exactly what you saw happen with your own eyes, or heard from people that are very close to you.
+
The testimony must include:
+
--
** when the events happened
** where they happened, in which city at the very least
** the full names of who did what
--
+
This is to:
+
** make it easier to verify the truth of the event
** uniquely identify the event so we don't count a single event multiple times

If you do provide all of the above, I add your report to a list of reports that I will maintain. This list does not exist yet because there were no valid reports yet.

Next consider this:

* are you sure that Falun Gong made the person do the bad thing, and that the person wouldn't have done it anyways?
+
Did someone from Falun Gong told the person to do it?
+
I bet that if you look into patients of psychiatrists, you will find more suicides than average. So should we ban psychiatry?
* are you sure that the order came from <<flg-lhz,LHZ>>, and that it was not just some disgruntled local leader using Falun Gong for his personal madness and doing things he did not approve?
+
Branch Davidians were inspired by Christianism. So should we ban Christianity? What about the majority of Christians who have never done anything bad?
* only statistics has any meaning, and it would require a very large number of reports to make up statistics, so you will likely be wasting your time. I will do my part and maintain a list however.
* if ask for FLG believers to compile a list of horrors they have suffered, which they have already been doing since the start of the persecution, I bet that their list will be much longer than yours, because they are so <<flg-organized,well organized>>

=== FLG does not have proof of their persecution claims

How much proof do you think they would be able to get when there is no freedom of press?

Do you think that forbidding a 70 million person religion could have gone smoothly?

Do you think the thousands of personal of accounts of human rights violations that exist are all fake, and don't indicate that many, many more have taken place but fallen under censorship?

Conversely, there is no reliable proof that FLG is bad as claimed by CCP that has been verified by international media.

=== Someone from movement X did something bad, therefore the movement should be banned

By this logic, everyone should go to jail. The law should only punish individuals.

The communist party, which has had continuous power since 1949, killed millions during the cultural revolution. Surely they must be banned, no?

But the CCP has changed so much since those days, I hear you say.

I agree. And <<flg-changed,so has FLG>>.

=== People from movement X are only in it for political power

For every desire of the masses, there will be amoral representatives that will step to use that power.

Still, those representatives cannot gain power if there is no backing desire from the society.

And at least the representatives have to pretend and to things for that group to retain their power.

=== Western media has exaggerated reports on FLG for propaganda reasons

Possibly true, but which reports are you talking about specifically?

All that I care about is:

* it is censored today
* if you do it you go to jail
* there were tens of millions of followers at the time of the ban

which I think are undeniable.

The only question that matters is: should it be banned or not?

=== Things I personally dislike about FLG

But also as explaining why I don't think it justifies the ban.

This section also gives me more credibility as a balanced critic >:-)

[[flg-religion]]
==== FLG downplays the fact that it is a religion

If asked if they follow a religion, I think most FLG practitioners will say no. E.g. they call themselves practitioners instead of believers.

But I think that most people in the West would classify FLG as a religion if they are told that it includes:

* absolute truth comes from an enlightened prophet, who is perfect and has super human abilities
* weekly meetings where they read from a sacred book
* prescribed daily medication exercise hours, somewhat like Muslim Salah prayers
* higher intelligent beings
* other dimensions
* aliens that looks like humans are amongst us, they gave us part of our modern technology

Or a cult, which is nothing but a new / small religion with negative connotation, and thus meaningless.

But consider this: how to classify what a religion is?

Some would answer: science is what everyone can perceive with their own senses.

But FLG followers claim to feel FLG energies when doing the exercises, and a few of them have the power of seeing the other dimensions.

On the other hand, how many of your friends have experienced the laws of quantum field theory or general relativity in a very direct way?

And aren't pro-democracy believers also taking actions based solely on a shared belief, possibly organized by a pro-democracy leader?

From a purely political point of view, the Religion classification would likely be more beneficial to FLG, since it the idea of freedom of religion carries considerable weight in the West.

[[flg-organized]]
==== FLG downplays the fact that it is highly organized

Many FLG practitioners claim that they are not at all organized.

But it is obvious from the size of the FLG related media, namely link:https://en.wikipedia.org/wiki/NDTV[NDTV television network], link:https://en.wikipedia.org/wiki/Epoch_Times[Epoch Times newspaper] and link:https://en.wikipedia.org/wiki/Shen_Yun_Performing_Arts[Shen Yun Performing Arts], that in practice they do have are a highly organized structure.

In particular, it is clear that <<flg-lhz,LHZ>> has direct ties with the FLG media organizations, e.g.:

* Shen Yun's 2018 libretto says that their Artistic Director and founder is "D.F." (likely an abbreviation for Da Fa, which is an abbreviation for Falun Gong Dafa, which is a full name of Falun Gong), with a picture of LHZ on top. It also amusingly says that D.F. is a "Distinguished Professor of Music and Dance at Fei Tian College in New York", which is likely where many of Shen Yun's dancers are trained, and therefore controlled by himself to a large extent

Like any other religion.

Once again, I feel that this lack of transparency hurts their cause more than it helps.

But then, what law are they breaking? Should we do something to punish them for it?

What if every practitioner feels in their hearts that they are actually free to do whatever they want without being coerced, and that they are simply doing what they believe is the right thing?

What about the people who participate in political movements such as pro-democracy? Aren't their political actions such as protests motivated in a very similar fashion?

==== FLG dislikes several other groups like homosexuals and some other religions

Like most old religions.

Democracy dislikes dictators.

You and I dislike certain personality traits without any logical reason.

What matters is that we treat everyone with respect and without bias at work, even if we don't like them.

But the law can't force you to like everyone.

If one specific FLG member breaks a law by discriminating someone, they should be punished just like anyone else.

==== FLG media is not transparent about its affiliation

Agreed, and it is a point that hurts more than helps their cause: e.g. New Tang Dynasty TV, Epoch Times and Shen Yun Dance group.

But are all media forced to state their affiliation?

If so, then we should force _all_ newspapers start taking pools of how many employees follow which religion, and put that in their print.

[[flg-medication]]
==== FLG believers are less likely to take necessary medication

Due to their beliefs in the healing power of FLG, which seems to have certain level of support on canonical texts TODO precise quotes.

This is a point that makes me worry, and I do believe that it is true for some believers, but consider:

* what matters are statistics. Maybe FLG people live longer than non FLG in average. But we will never have statistics because of censorship: http://skeptics.stackexchange.com/questions/27529/have-many-falun-gong-practitioners-forgone-medical-treatment-and-died-of-treatab
* maybe people should be link:https://en.wikipedia.org/wiki/Suicide_legislation[allowed to choose how they want to die], not to take medication if they don't want to
* maybe the number of people killed during persecution vastly outnumbers those who died because they would not take medication
* several religions, including Christianism have miraculous cure claims. My impression is that claims were mostly notable in the old times apparently, likely because people noticed that Christians were still dying of all kinds of diseases like everyone else, no matter how devout!
* maybe the main reason why communists banned FLG is the political threat it posed, but that a ban was unjustified given the situation. Christian crosses are being taken down as of 2016, have they stopped taking their medications as well?
* maybe many of those people would also have died soon even if they had taken medication
* maybe not all Falun Gong believers thought that it was wise to stop taking medication. But their religion was banned anyways. Who can agree and follow all the innumerable prescriptions of any religious or legal system?
* all the following also reduce people's lifespan:
+
--
** riding motorcycles vs cars / buses
** smoking
** moving to a poor country to do charity there
** eating fast food
--
+
Forbidding them also has huge humanitarian costs (more expensive vehicles, creation of a black market, ...). So why not forbid them as well?

[[flg-lhz]]
==== FLG is dangerous because LHZ has too much power over followers

LHZ (Li Hongzhi) is the creator of FLG: link:https://en.wikipedia.org/wiki/Li_Hongzhi[], or as I prefer to call it, its <<flg-religion,prophet>>.

I agree that there is danger in every religion, and specially new religions.

However the same point can be made about political parties and in particular the CCP and its chairman.

Couldn't a charismatic leader chairman gain more and more power (like Xi seems to be doing), and eventually start a war and kill millions? Or just kill some minority which is not happy about the situation.

Similarly, any charismatic leader of a pro democracy movement could become the leader of a terrorist organization.

If you ever want democracy, you will have to learn to accept the beliefs of others, and only punish them when they actually break a law.

Finally, LHZ was born in 1951, so will die in 20 unless FLG is true and a miracle happens, and then this argument will become invalid.

From what I hear, LHZ has always maintained that he is the only source of truth on FLG, and therefore, so his death will very likely remove any danger once and for all.

Furthermore, it also seems to me that FLG is clearly anti-violence and self-harm, so I wonder how many would follow a contradictory order such as killing or suicide?

It is also interesting to look into the https://en.wikipedia.org/wiki/Jonestown case. When the suicide order came, most people wanted out! Without physically controlling the followers, I don't think you can make them do much.

==== Some FLG people make phone telemarketing

I've seen that happen, they made phone calls to people in China to explain why FLG is good, and I disapprove of it.

Visual ads on the street on Internet I can stand, but not any kind of advertising that generates notifications on my feeds.
