= FAQ
:toc:
:toc-title:
:toclevels: 5
:numbered:

== Why are you attacking websites with censored keywords?

<<the-attack, The attack>>.

To <<effective,destroy the firewall>>.

This would then end censorship.

And then <<dictator-needs-gfw,I believe>> that this would also <<why-end-dictatorship,end the dictatorship>>.

The keyword attacks increase the cost of censorship.

If commies censor things, they will get worse IT technology, and thus become less rich and militarily powerful.

Maybe this hurts my argument, but Hillary agrees: https://youtu.be/d3dE_LDz_9E?t=1681 :-)

Since all they care about, like any other politicians, is power, the only way to make them stop censorship is to make the cost of censorship higher than not censoring.

Without the threat that China will be less technologically, and therefore militarily advanced, there is no incentive for the CCP to destroy the firewall.

The goal is to put them in a position where they have to choose between either:

* having military power
* remaining a dictatorship

but not both, since having both means that they will <<war,start WW3 and destroy humanity>>

[[harm-programmers]]
=== Do you want to harm the Chinese programmers?

No.

This is not a revenge of any kind.

I know I am harming you on the short term, and I don't like myself for it.

But I believe that this harm is a necessary means to reach my real goal, which is to destroy the firewall, and the dictatorship.

Don't you think it is worth a try? Destroying the firewall, would <<why-end-dictatorship,enormously benefit>> not only Chinese programmers, but every single other Chinese person too.

Once the firewall is destroyed, which <<dictator-needs-gfwe,may to destroy the dictatorship>>, I want China to develop the best science and technology in the world. I would even migrate there if given a good job.

And by the way, by contributing to open source, I am already helping China, and all underdeveloped countries become stronger.

[[why-end-dictatorship]]
== Why do you want to end the dictatorship?

Because I think that this would make China, and the world:

* <<richer,richer>>
* less likely to get into <<war,WW3>>

[[richer]]
=== Why would democracy and freedom of speech make China richer?

There is infinite debate about this out there, some examples:

* http://www.becker-posner-blog.com/2011/05/can-poor-countries-afford-democracy-becker.html
* https://www.quora.com/Is-democracy-or-authoritarianism-better-for-developing-countries

Society can be richer when people know that they can do their startups, get rich, and stay in the country without fear of being persecuted unfairly and losing everything.

Maybe China was poor because of Mao's crazy communist regime. Similar regimes also made Russia poor. And yes, before that exploitation by the West may have been a factor.

Definitely, the current regime is better than Mao's, but just imagine how rich China could be if it had more freedom and justice.

Imperial China lost the race for the Industrial Revolution. Will another dictatorship be able to stay on top of the next technological revolution?

[[war]]
=== Why would democracy and freedom of speech make China less likely to start a war?

This has been discussed to death:

* https://en.wikipedia.org/wiki/Democratic_peace_theory
* https://en.wikipedia.org/wiki/Perpetual_Peace:_A_Philosophical_Sketch

Some arguments include:

* the people who will actually fight and die on the front can't vote against it
* dictators have huge power, so if they put it in their heads that they want to start a war, it is much harder for sensible people to stop them
* dictators need to keep the people in fear all the time to keep their power, and a war is a great way to achieve that

=== Censorship is necessary to protect China from harmful USA propaganda

I don't think this is below them, but:

* without censorship, you would be much richer and stronger, and more able to defend yourselves
* why does China also censor its own people in addition to foreign propaganda?
* maybe this fear is greatly emphasised by the Chinese government beyond truth just to help them keep control of the country by fear and maintain their own power. Can the Americans really have that much influence in your country?
* maybe the regions that want to split from China feel like China is not giving them anything back, and they are themselves looking for allies outside of China to help them split. With democracy, people are more likely to get what they want, and there will be split parties and votes.
* the same argument can be used to justify any action, no matter how bad. E.g.: we must put all who criticize the government in jail, or else they will make China less united and weaker against the USA!

=== The Chinese masses are still uneducated, and not fit for free speech and democracy

When will they be ready? Who decides? What if they think that they are ready now?

[[effective]]
== Will the keyword attacks really help to destroy the firewall?

=== Embargoes make the dictatorship stronger

In other words, if programming websites get blocked, there will be less good programmers to fight against the dictatorship

The <<attack,keyword attack>> is basically an embargo

This is a good point, and one that does make me think.

. The commies calculate their actions very well to stay in power.
+
Why don't they just take down the entire Internet like they did in Xinjiang in 2010?
+
Because that would hurt them:
* people would go mad, and revolt
* people would work less efficiently, making the country, and thus themselves, poorer
+
So this puts pressure on them to take away the firewall.
. Programmers are more likely to develop better Firewall climbing tools if SO is blocked
. If we don't take any action to show our dissatisfaction, the dictatorship never ends.
+
The commies exist like any other organization for a sole purpose: maintain their own power.
+
If nothing is done to show dissatisfaction, they will never give up on that power.
+
There are two extremes of action (both which _I don't_ support):
* everyone become a willing mindless slave of the leader: perfect stability
* everyone take up arms and do terrorism: perfect instability
+
But between those two extremes, what is the right measure? I think that saying nothing is too close to stability.
+
I do see that one alternative scenario is that if we do nothing, maybe there will be more and more contact with Western countries, and the Chinese will see for themselves that we are not that bad, and eventually request democracy.
. Even if programmers get very powerful, it is not very likely that they will succeed to undo the dictatorship, they simply don't have enough power.
+
I'd rather have a less strong dictatorship, than one with good programmers.

There is already a lot of literature about this, specially in the cases of Cuba and North Korea. It is basically a libertarian vs conservative / Cato vs Heritage thing in the US:

* https://www.cato.org/publications/commentary/no-embargo-harms-cubans-gives-castro-excuse-policy-failures-regime
* https://www.heritage.org/trade/report/why-the-cuban-trade-embargo-should-be-maintained
* http://www.slate.com/articles/news_and_politics/the_big_idea/2006/08/thanks_for_the_sanctions.html

=== What you are doing will never have any effect

That is true with high probability, just like any other individual which tries to influence 1B people.

Every action is statistical: I just push the balance a little bit towards freedom.

This FAQ and any talk is useless. You and I are wasting out times here.

The possibility of blocking Stack Overflow and GitHub is 1000x more useful than any talk, but it is still useless.

However, potentially blocking those websites takes 0 of my time, I just leave the content there, so it is worth my time.

To have an idea, in 2015 there are about:

* 20M developers in the world
* 2M in China : https://www.quora.com/Approximately-how-many-programmers-are-there-in-the-world http://www.techrepublic.com/blog/european-technology/there-are-185-million-software-developers-in-the-world-but-which-country-has-the-most/
* 5M Stack Overflow users http://data.stackexchange.com/stackoverflow/query/227868/select-count-from-users
* TODO I wonder what percentage of GDP those programmers control. I'll bet any programmer on Stack Overflow is 5x more powerful than the average Chinese.

And if we never start somewhere, nothing will ever happen.

=== Stack Overflow could be blocked at no cost by the Chinese government

Hitting the block button has of course no cost.

The cost of blocking Stack Overflow lies of course in the loss of information, and slower technological development.

=== Keyword attacks could be used by certain CCP political groups to justify blocking off the entire external Internet, and make the dictatorship even more pervasive

It is a risk, but it would make China drastically <<richer,less powerful>>, so at least they wouldn't be able to start or sustain <<WW3>>. So I don't think it will go that way.

[[dictator-needs-gfw]]
== Would ending the great firewall truly end the dictatorship?

Not 100% sure.

In Russia for example, the Internet is relatively free, but the government controls most professional media, which is what most people end up seeing, by suing dissidents media out of business.

But on the other hand Russia is already much freer than China.

Although I don't like them, I can't deny one thing: the commies are smart, and when they do something (e.g. censorship), it tends to keep them in power.

== This is your personal problem, we have nothing to do with it, stop punishing us for it

We have to fight for justice for our fellows, or else when injustice happens to us, no one will fight for use either.

Every form of protest incurs some damage. E.g., if we manifest on the street, it generates a traffic jam.

I don't like it, but I think it is worth it.

How can you be that certain that your children won't have dissident ideas and be punished unfairly for them?

Intolerance is a risky way to live.

== If anyone disagrees with the government they must be punished to keep the stability of the country

Destroying diversity is the best way to reach a point where everyone can agree to start a new big war and destroy everything.

The CCP thrives on the excessive fear it instigate into its own people.

How can society improve, if we are never allowed to try new things out?

Change does not require violence. Violence happens because the government punishes any dissidence, even if pacific, to retain its own power.

In democracies, radical policy changes happen without dropping a single drop of blood.

== You are using Stack Overflow in a way that it was not meant to be used, so what you are doing is in principle wrong

Any act of protest will use things in ways that it was not meant to be used.

For example, the street is not meant to showcase protest banners, it is meant to be a passageway for cars.

Making a statement where no one will ever see it, like a personal website, is sure to have no effect.

Finally, it is up to the Stack Overflow community to decide what is right or wrong, and so far the consensus is go ahead:

* http://meta.stackoverflow.com/questions/298950/are-political-profiles-that-could-possibly-affect-the-participations-of-other-us
* http://meta.stackoverflow.com/questions/267368/are-political-avatars-and-profiles-ok
* http://meta.stackoverflow.com/questions/299882/can-a-username-be-considered-spam
* http://meta.stackexchange.com/questions/286082/does-the-be-nice-policy-require-se-users-to-be-nice-to-people-who-are-not-se-u/286090#286090, see public figure comments

Much of the best art and technology is about using something in a way that it wasn't meant to be used.

== There are bad things happening all over the world, why don't you fight for those causes as well / instead?

We have to choose the one we think is the worst, and focus on it.

What is worse is a subjective choice. For me:

* I love China and my Chinese wife
* I hate dictatorships, and China is the largest one

My SO username and protest time are not infinite.

== You are not Chinese, you can't interfere in Chinese politics

. We live in the same world.
+
If China's <<richer,economy>> is bad, my economy is worse.
+
If China's environment is bad, my environment is worse.
+
If China starts a <<war>>, I might have to fight it.
. If I lived under a dictatorship, I would welcome foreign intervention.
+
Even if you don't, I know several who do.
. You have been brainwashed by the commies who say that all foreigners are bad :-)
+
The commies do this because most foreign countries are telling the Chinese to get rid of the dictatorship.
+
Most foreigners actually want what is best for China.
. You can't do anything about it.
+
I don't like this argument, but in the end, this is what all politics comes down to: power.
+
I recognize that in that sense, I may be similar to the CCP and any other political party.

=== You are not Chinese, you have been brainwashed by the USA know nothing about China

Everyone is "brainwashed" by their environment.

I don't doubt that you know more about China than me.

If you know something I don't, please tell me, I always want to learn.

But if you are Chinese, also consider that you have been brainwashed by the commies, and likely more than me since you live in a dictatorship.

== What is the goal of this repository?

. Inform
. Increase the cost of censorship for Git web interfaces

=== This repository is completely biased against the Chinese Government!

I prefer the term focused :-)

That being said, I take the agenda of information sources very seriously.

E.g. I try to clearly classify Communist Party and Falun Gong linked sources.

== In the Tweet you say "correctional facility", but reeducation through labour has been abolished

My bad https://twitter.com/cirosantilli/status/579270450984984576[here], the precise term is "jail". I'm _not_ talking about: https://en.wikipedia.org/wiki/Re-education_through_labor Unfortunately I can't edit a Tweet.

== Are you making programming contributions with the main intent of promoting your policital agenda?

No, that is just a side effect.

If that were the case, I would definitely target more widely technologies, in particular Web and JavaScript, instead of obscure things like C and assembly in which I have spent tons of my time.

Also, as I've said elsewhere, my actions are very unlikely to have any actions. Much more likely to have any action, would be for me to become rich and powerful first, and the best way to do that is to invest in whatever I think is most useful.

Actually, it can even be argued that I'm somewhat irrational, since I would much more likely become rich and powerful by bowing down to the CCP and trying to get their money instead.

On the other hand, becoming rich and powerful is also highly unlikely, so maybe I'm just taking a low risk low reward path?

I have very little free time, and will never do something for political resaons, only things that interst me technically.

Finally, do you really think I'd be able to make such awesome projects if I had primarily politicial considerations in mind? XD

=== Are you making trivial edits on questions just to spam your name further?

No.

I just think that website is great, and want to push it to perfection, in particular with better Google keyword hits, and uniform gramatically correct titles.

If you think that any of my edits were harmful, please ping me and open a meta thread to discuss specific edits, and I will comply with consensus.

== Irrelevant personal questions

=== Are you a radical?

Radical: I don't consider myself a radical because I actually have doubts about doing this sometimes.

Also I don't consider the Chinese Government Evil or anything like that. To me, it's just another non-democratic empire like the Qing Dynasty. 共产朝 as I call them. But alas, I'm not the inventor of the expression: http://web.archive.org/web/20161025220242/http://tieba.baidu.com/p/752094668

I never get mad. Only a slightly sad or annoyed sometimes.

But I do admit that I am hard headed like almost all humans, and it is very unlikely that anything anyone says will change my mind about subjective political matters.

In the end I just end up thinking about new replies to those arguments and adding them to this FAQ.

But maybe no radical ever considers himself radical? Hmmm...

=== Are you a SJW?

SJW: there is a seed of SJW in me.

One major difference between me and the stereotypical SJW is that I never engage in lengthy discussions.

I believe that you cannot change people's mind's, and that learning tech is more worthy of my time.

I limit myself to listening as much as I can to learn new arguments.

So the rationale of my actions is _not_ to convince anyone, but rather:

* increase the monetary cost of censorship by binding politics to tech
* group up like minded people who don't like censorship

=== Do you hate China?

On the contrary. China is my favorite country. It has many, many wonderful things. As Bjarne said:

____
There are only two kinds of programming languages: those people always bitch about and those nobody uses
____

I only focus here on negative things to provide content that will activate the Great Firewall.

If it wasn't for the dictatorship, I would seriously consider living there.

=== Are you doing this because of your wife?

Of course not. I am, just like you, a completely selfless being, who only cares about what is best for the world as a whole.

=== Are you doing this because it makes you feel important?

No, I am a selfless human being, only concerned with the well being of humankind.

=== Would you be doing this if you were in China?

Not with my real name attached to it.

=== Do you believe in or practice Falun Gong?

No.

== Is your campaign funded or otherwise supported by some organization?

Nope.

But then, a shady supporting organization might require that I don't disclose their support, so maybe the best answer is that you will never know for sure.

Of course, a hidden support would represent a reputation hit for both such organization and for me, which makes it less likely that I would have accepted or had such an offer.

Also consider my motivation. If your mother in law were put into jail unfairly for 15 days, for following the same religion that your wife follows, and if you had a social media presence, wouldn't you be tempted to do the same?

What about you, are you funded by the CCP?

See also: https://github.com/cirosantilli/china-dictatorship/blob/48a95bf57a16b85619a6ae68702d18c9a5078797/FAQ.md#flg-has-been-funded-by-the-us-government-at-least-once-therefore-it-is-evil

=== Does your employer support this?

My employer has nothing to do with this.

He doesn't approve or disapprove of the Chinese government or of my private actions.

The only thing that my employer _does_ believe in is that employees can have their own political opinions, and that this should not affect hiring decisions.

Obviously, this action limits my ability to lead high profile deals with China.

Also I'm quite curious if this would limit my ability to go to China for business, but I haven't applied for a visa since I've started this.

But my employer believes that inclusion and non-discrimination is more valuable.

I will always do my best to not let my personal opinions affect my professional decisions, as that would be unfair to my employer.

=== Don't you have anything better to do?

In 1989, a beautiful thing called the World Wide Web was invented.

The Internet gives everyone the magic power of writing something, and having million people read it for free!

This is how much time I spend on this to give you an idea:

* every week or two, someone sends me a message, I reply with "read the FAQ", and usually update 
* I follow https://www.reddit.com/r/China amongst many other programming subs, and all major bad news show up there
* when something bad enough comes up, I go to https://chinadigitaltimes.net/china/sensitive-words-series/ and update <<attack,my keyword attack>>. I've only been updating it on Stack Overflow these days, since GitHub does not show my profile name prominently.

Then I just contribute to programming websites exactly as I would if I weren't making this campaign.

== Were you influenced by the Cute cat theory of digital activism?

https://en.wikipedia.org/wiki/Cute_cat_theory_of_digital_activism

Nope, someone told me about it after a while, but it is basically what I'm doing.

You can never invent anything new anymore nowadays.

== People in China have already considered democracy, and rejected it

OK, shall we put that to an anonymous vote just to make sure?

Dear sir or madam: so you want more control over your government? y/n

== Are for a violent revolution to overthrow the CCP?

No, I'm against physical violence.

And furthermore it would never work, since the CCP controls the army.

I propose instead a revolution of ideas, and efficient link:https://en.wikipedia.org/wiki/Nonviolent_resistance[nonviolent resistance].

Where efficient means: if you are a dissident, use privacy technology, and weight well the benefit vs risks of your actions.

You are often more useful to the cause outside of jail than inside.

== Why do you say China is a dictatorship?

True, I'm using the word in an extended / jokingly sense.

Maybe authoritarian is a more precise term.

In particular, dictatorships are harder to sustain than authoritarianism, since it generally implies even less freedom.

Dictatorship is becoming link:https://www.nytimes.com/2018/03/07/world/asia/china-xi-jinping-party-term-limit.html[more and more precise under Xi] however.

[[attack]]
== What is a screen name keyword attack?

Adding censored words to your username: https://stackoverflow.com/users/895245

This only works on websites that show usernames everywhere.

This then leads to your username appearing on thousands of pages, depending on how much you contribute to the website.

It is also possible to do it with with images, although this is less effective in taking down websites since images are harder to track automatically.

This type of attack is essentially an embargo.

== Falun Gong

=== Do you support FLG, or just use it because it is a censored?

I don't support FLG specifically, only freedom of religion.

I use it in my usernames simply because it is the most banned and censored one in China today.

I believe that individuals should only be put in jail for what they do, not for what they believe.

I consider FLG a religion, and I am against its ban, as I am for all other religions.

Also I believe that freedom of speech and democracy imply that FLG and other religions will exist. If you want freedom, you have to accept other people's choices.

Otherwise, democracy and communism can also be considered as religions, and banned.

=== Do you support FLG just because your wife and mother-in-law do it?

Not consciously.

I think that 70 Million people getting completely squashed by the Party illustrates extremely well the dangers of the dictatorship.

[[flg-changed]]
=== Falun Gong is completely different in the West than it was in China

I believe that it has changed.

But isn't that the case of every cultural religious movement that migrates to a completely new culture?

Main points which may have changed:

* It has become more organized.
+
But why shouldn't they organize to defend themselves now that they have the chance without being put into prison?
+
The CCP is highly organized and has way more resources.
* Less emphasis is given to the religious / mystical aspect, and more to the corporal exercises, and health aspect.
+
This may be because people in the "West" are:
** are "scientific-educated" atheists who wouldn't go for a "religion"
** already have other religions, which would view FLG as a taboo

Also maybe only the richest and most educated believers managed to escape China, and thus the movement carried that bias outside China.

If you know more ways in which it may have changed, let me know.

But once again, we can know nothing for sure about the past in China because of censorship.

Even if you saw something yourself, how can you be sure that it is representative?

And if it has changed, now that it has changed, maybe China should unban it?

=== FLG has been funded by the US government at least once, therefore it is evil

1.5M USD in 2010 for a FLG controlled internet freedom group http://news.bbc.co.uk/1/hi/world/americas/8678760.stm

But well, if you are going to do something anyways, and someone offers you money, why wouldn't you take it?

Taking the money does of course give a "bad impression" that someone is trying to buy influence, but does it in itself imply that you are doing something bad?

But do you really think that the US government paid that to buy influence in FLG? What would they force upon that FLG group that they didn't already want to do? Isn't it more likely that the US government wanted them to continue doing exactly what they were doing?

Every government funds groups it supports, it is an all out war I suppose. Compare that to the propaganda funds of the CCP.

What about the funding of political campaigns, which vastly outnumbers 1.5M USD every year?

=== FLG is illegal in China, we must follow the law

This might be a bad law that should be changed.

It was perfectly legal for Nazis to kill Jews. Does it make that right?

=== FLG is fake

The same can be argued about any other religion or political belief of type: it is better if we organize society in this or that way.

How can you disprove their belief, when as in any other religion, every affirmation made hinges on "miracles only happen around when true believers are around" or "only true believers can perceive evidence in their hearts / minds directly". He died of cancer? Not a true believer.

Conversely, do you understand the full sequence of experiments that imply quantum field theory? Have you seen videos of those experiments? Have you attended live demonstrations? Do you understand the construction of the experimentation apparatus? Yet, why do you believe it?

More importantly: what do you propose that should be done about it?

==== FLG is a very new religion and therefore fake

The Romans called Christianism the "Cult of Jesus".

If I tell a lie today, will it become true in a thousand years? Or a truth today become a lie?

Try sending an email to LHZ asking him to prove his powers to you :-)

=== Many people both are against censorship and FLG

I know that, and that supporting FLG is "bad" for my public image with most Chinese, including those that are against censorship.

But without censorship, there will be democracy, and with democracy FLG followers will have voting rights, and FLG will become legal.

I think the situation is very similar to Scientology in the USA today: most people dislike it, but believe that you can believe whatever you want.

Democracy and Communism can also be considered as religions and persecuted.

Isn't it convenient when a dictatorship gets rid of those weirdos for you? But not so much when suddenly you or your family is the weirdo...

=== Many people say they do FLG only to get VISAs to the USA

Heard this a few times, but I don't see how this is relevant at all:

* if they are not really FLG believers, this says nothing about the real FLG believers
* if they are, then why wouldn't they seek a VISA, since they are in constant threat of going to jail?

=== Why do you say that democracy is a religion just like FLG?

Because it also specifies irrational and fundamental aspects of how one should live, notably voting and freedom of speech.

=== I have personally seen people do bad things because of Falun Gong

Either direct suicide or <<flg-medication,dying because of not taking medication>>.

First, I'm not saying I don't believe you, and I'm sorry about what happened.

But your testimony is worthless unless you give the following:

* clear unique personal identification
+
There are basically two ways to do that:
.  Links between a notable social media presence that is hard to achieve, e.g. Twitter with many followers, Stack overflow with a lot of rep, and the account
.  Your testimony is done in video form on YouTube clearly showing your face as you make it
+
Either of those must contain / link to information that uniquely identifies you. Generally, full name, city and date of birth is enough.
* a precise testimony that states exactly what you saw happen with your own eyes, or heard from people that are very close to you.
+
The testimony must include:
** when the events happened
** where they happened, in which city at the very least
** the full names of who did what

If you do provide all of the above, I add your report to a list of reports that I will maintain. This list does not exist yet because there were no valid reports yet.

Next consider this:

* are you sure that Falun Gong made the person do the bad thing, and that the person wouldn't have done it anyways?
+
Did someone from Falun Gong told the person to do it?
+
I bet that if you look into patients of psychiatrists, you will find more suicides than average. So should we ban psychiatry?
* are you sure that the order came from LHZ, and that it was not just some disgruntled local leader using Falun Gong for his personal madness and doing things he did not approve?
+
Branch Davidians were inspired by Christianism. So should we ban Christianity? What about the majority of Christians who have never done anything bad?
* only statistics has any meaning, and it would require a very large number of reports to make up statistics, so you will likely be wasting your time. I will do my part and maintain a list however.

=== FLG does not have proof of their persecution claims

How much proof do you think they would be able to get when there is no freedom of press?

Do you think that forbidding a 70 million person religion could have gone smoothly?

Do you think the thousands of personal of accounts of human rights violations that exist are all fake, and don't indicate that many, many more have taken place but fallen under censorship?

Conversely, there is no reliable proof that FLG is bad as claimed by CCP that has been verified by international media.

=== Someone from movement X did something bad, therefore the movement should be banned

By this logic, everyone should go to jail. The law should only punish individuals.

The communist party, which has had continuous power since 1949, killed millions during the cultural revolution. Surely they must be banned, no?

But the CCP has changed so much since those days, I hear you say.

I agree. And <<flg-changed,so has FLG>>.

=== People from movement X are only in it for political power

For every desire of the masses, there will be amoral representatives that will step to use that power.

Still, those representatives cannot gain power if there is no backing desire from the society.

And at least the representatives have to pretend and to things for that group to retain their power.

=== Western media has exaggerated reports on FLG for propaganda reasons

Possibly true, but which reports are you talking about specifically?

All that I care about is:

* it is censored today
* if you do it you go to jail
* there were tens of millions of followers at the time of the ban

which I think are undeniable.

The only question that matters is: should it be banned or not?

=== Things I personally dislike about FLG

But also as explaining why I don't think it justifies the ban.

This section also gives me more credibility as a balanced critic >:-)

==== FLG downplays the fact that it is a religion

If asked if they follow a religion, I think most FLG practitioners will say no. E.g. they call themselves practitioners instead of believers.

But I think that most people in the West would classify FLG as a religion if they are told that it includes:

* absolute truth comes from an enlightened prophet, who is perfect and has super human abilities
* weekly meetings where they read from a sacred book
* prescribed daily medication exercise hours, somewhat like Muslim Salah prayers
* higher intelligent beings
* other dimensions
* aliens that looks like humans are amongst us, they gave us part of our modern technology

Or a cult, which is nothing but a new / small religion with negative connotation, and thus meaningless.

But consider this: how to classify what a religion is?

Some would answer: science is what everyone can perceive with their own senses.

But FLG followers claim to feel FLG energies when doing the exercises, and a few of them have the power of seeing the other dimensions.

On the other hand, how many of your friends have experienced the laws of quantum field theory or general relativity in a very direct way?

And aren't pro-democracy believers also taking actions based solely on a shared belief, possibly organized by a pro-democracy leader?

From a purely political point of view, the Religion classification would likely be more beneficial to FLG, since it the idea of freedom of religion carries considerable weight in the West.

==== FLG downplays the fact that it is highly organized

Many FLG practitioners claim that they are not at all organized.

But it is obvious from the size of the FLG related media, namely NDTV and Epoch Times, that in practice they do have are a highly organized structure.

Like any other religion.

Once again, I feel that this lack of transparency hurts their cause more than it helps.

But then, what law are they breaking? Should we do something to punish them for it?

What if every practitioner feels in their hearts that they are actually free to do whatever they want without being coerced, and that they are simply doing what they believe is the right thing?

What about the people who participate in political movements such as pro-democracy? Aren't their political actions such as protests motivated in a very similar fashion?

==== FLG dislikes several other groups like homosexuals and some other religions

Like most old religions.

Democracy dislikes dictators.

You and I dislike certain personality traits without any logical reason.

What matters is that we treat everyone with respect and without bias at work, even if we don't like them.

But the law can't force you to like everyone.

If one specific FLG member breaks a law by discriminating someone, they should be punished just like anyone else.

==== FLG media is not transparent about its affiliation

Agreed, and it is a point that hurts more than helps their cause: e.g. New Tang Dynasty TV, Epoch Times and Shen Yun Dance group.

But are all media forced to state their affiliation?

If so, then we should force _all_ newspapers start taking pools of how many employees follow which religion, and put that in their print.

[[flg-medication]]
==== Many people have died because they stopped taking medication because of Falun Gong

http://skeptics.stackexchange.com/questions/27529/have-many-falun-gong-practitioners-forgone-medical-treatment-and-died-of-treatab

This is a point that makes me worry, and I do believe that this has happened, that but consider:

* what matters are statistics. Maybe FLG people live longer than non FLG in average. But we will never have statistics because of censorship.
* maybe people should be link:https://en.wikipedia.org/wiki/Suicide_legislation[allowed to choose how they want to die], not to take medication if they don't want to
* maybe the number of people killed during persecution vastly outnumbers those who died because they would not take medication
* several religions, including Christianism have miraculous cure claims. My impression is that claims were mostly notable in the old times apparently, likely because people noticed that Christians were still dying of all kinds of diseases like everyone else, no matter how devout!
* maybe the main reason why communists banned FLG is the political threat it posed, but that a ban was unjustified given the situation. Christian crosses are being taken down as of 2016, have they stopped taking their medications as well?
* maybe many of those people would also have died soon even if they had taken medication
* maybe not all Falun Gong believers thought that it was wise to stop taking medication. But their religion was banned anyways.
* all the following also reduce people's lifespan:
+
--
** riding motorcycles vs cars / buses
** smoking
** moving to a poor country to do charity there
** eating fast food
--
+
Forbidding them also has huge humanitarian costs (more expensive vehicles, creation of a black market, ...). So why not forbid them as well?

==== FLG is dangerous because LHZ has too much power over followers

Note: LHZ is the creator of FLG: link:https://en.wikipedia.org/wiki/Li_Hongzhi[]

I agree that there is danger in every religion, and specially new religions.

However the same point can be made about political parties and in particular the CCP and its chairman.

Couldn't a charismatic leader chairman gain more and more power (like Xi seems to be doing), and eventually start a war and kill millions? Or just kill some minority which is not happy about the situation.

Similarly, any charismatic leader of a pro democracy movement could become the leader of a terrorist organization.

If you ever want democracy, you will have to learn to accept the beliefs of others, and only punish them when they actually break a law.

Finally, LHZ was born in 1951, so will die in 20 unless FLG is true and a miracle happens, and then this argument will become invalid.

From what I hear, LHZ has always maintained that he is the only source of truth on FLG, and therefore, so his death will very likely remove any danger once and for all.

Furthermore, it also seems to me that FLG is clearly anti-violence and self-harm, so I wonder how many would follow a contradictory order such as killing or suicide?

It is also interesting to look into the https://en.wikipedia.org/wiki/Jonestown case. When the suicide order came, most people wanted out! Without physically controlling the followers, I don't think you can make them do much.

==== Some FLG people make phone telemarketing

I've seen that happen, they made phone calls to people in China to explain why FLG is good, and I disapprove of it.

Visual ads on the street on Internet I can stand, but not any kind of advertising that generates notifications on my feeds.
