#!/usr/bin/env bash
./push-mirrors-bump-package-json-version
git add package.json
git commit -m 'bump package.json'
npm publish
git push git@gitlab.com:cirosantilli/china-dictatorship.git
git push git@bitbucket.org:cirosantilli/china-dictatorship.git
