#!/usr/bin/env bash

# Create a tag and push to EVERY supported mirror.
# https://github.com/cirosantilli/china-dictatorship#mirrors

set -eux

# Update repo.
new_version="$(./push-mirrors-bump-package-json-version)"
./push-mirrors-bump-setup-py-version
git add package.json
git add setup.py
git commit -m 'bump package version'
git tag -m "$new_version" "$new_version"
./push

# NPM package.
# Updates package.json version, which other systems read if possible.
npm publish

# Python package.
# Initial setup:
#sudo apt install python3-testresources
#python3 -m pip install --user --upgrade setuptools wheel
# Initial one time setup.
#python3 -m pip install --user setuptools wheel twine
cp README.adoc README.html china_dictatorship
python3 setup.py sdist bdist_wheel
# Asks for password every time, unless you setup ~/.pypirc.
# But I don't want to put a plaintext password in there.
# https://stackoverflow.com/questions/57935191/twine-is-asking-for-my-password-each-time-how-to-use-the-pypirc
twine upload dist/*
rm -rf build dist *.egg-info

# Push to other git mirrors.
git push git@bitbucket.org:cirosantilli/china-dictatorship.git
git push git@gitlab.binets.fr:ciro.duran-santilli/china-dictatorship.git
# Nah.
#git push https://gitee.com/cirosantilli/china-dictatorship.git
