#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const json = JSON.parse(fs.readFileSync('package.json'));
const version_split = json.version.split('.');
json.version = `${version_split[0]}.${version_split[1]}.${parseInt(version_split[2]) + 1}`;
fs.writeFileSync('package.json', JSON.stringify(json, null, 2) + '\n');
console.log(json.version);
