= 三朝罪恶元凶王沪宁
:china-dictatorship-media-base: https://raw.githubusercontent.com/cirosantilli/china-dictatorship-media/master
:cirosantilli-media-base: https://raw.githubusercontent.com/cirosantilli/media/master
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

toc::[]

== 【23】三朝罪恶元凶王沪宁

大陆修宪香港恶法台湾武统朝鲜毁约美中冷战等都是王沪宁愚弄习思想极左命运共同体的大策划

中共窃国这半个多世纪所犯下的滔天罪恶，前期是毛泽东策划的，中期6.4前后是邓小平策划的，后期是毛的极左追随者三朝罪恶元凶王沪宁策划的。

王沪宁高小肆业因文革政治和情报需要保送“学院外语班“红色仕途翻身，所以王的本质是极左的。他是在上海底层弄堂长大的，因其本性也促成其瘪三下三滥个性，所以也都说他有易主“变色龙””哈巴狗“的天性。大陆像王沪宁这样学马列政治所谓"法学"专业的人，在除朝鲜古巴所有国家特别是在文明发达国家是无法找到专业对口工作必定失业，唯独在大陆却是重用的紧缺“人才”，6.4后中共信仰大危机更是最重用的救党“人才”。这也就是像王沪宁此类工农兵假“大学生”平步青云的原因，他们最熟悉毛泽东历次运动的宫庭内斗经验手段和残酷的阶级斗争等暴力恐怖的“政治学”。王沪宁能平步青云靠他这马毛伪“政治学”资本和头衔，不是什么真才实学，能干实事有点真才实学的或许在他手下的谋士及秘书班子中可以找到。王沪宁的“真才实学”只不过是一个只读四年小学的人，大半辈子在社会上磨炼特别是在中共官场滚打炼出的的手段和经验而已，他和习近平等保送的工农兵假“大学生”都一样，无法从事原“专业”都凭红资本而从政。六四学运期间各界一边倒支持学生，王沪宁一度去法国躲避和筹谋，他还加入了反学运签名，成为极少有的反学运者仕途突显，在六四和苏联垮台后中共意识形态危机，江泽民上台看上唯一能应急的王沪宁聚谋士泡制的"稳定统一领导"和之后的"新权威"谬论。左转被邓小平南巡阻止后，王策划顺邓经济改革却将政治改革逐步全面终止和倒退，泡制“三个代表”为极左转建立庞大牢固的红色既得利益集团。因此六四后各重大决策和危机难题都摆在中共中央政策研究室王沪宁桌面上，使王沪宁成了此后中共三朝都无法摆脱的幕后最有决策性实权的人，中共中央政策研究室是王为其野心巨资经营几十年，聚众谋士的间谍情报汇总研究的特务机关和策划制定决策重要机构与基地，王沪宁本人和决定其仕途关键的首任岳父及家属就有情报工作背景。中央政研室重要到王沪宁入常后为了死抓这中共情报与决策大权，宁可放弃国家副主席和中央党校校长。后再加个除习外唯他担任的中共几核心领导小组之一的“不忘初心牢记使命”主题教育工作小组组长。此后他把持的舆论必将以宣传“不忘初心牢记使命”为主，打造众所周知的所谓“习思想”其实是”王思想“。王自从主导中央政研室开始决策后，策划中止邓小平的与美妥协路线回归毛极左的反美路线。帮助前南斯拉夫提供情报打落美机放中使馆引发炸使馆事件，以此掀起六四后唯一的全国大规模游行并借此反美而起家。后又帮江泽民提供法轮功会是超过中共组织的情报，策划决策镇压迫害开始并没有把矛头指向江的法轮功群体，策划决定阻止党内外近三十年来平反六四的呼声。

胡温时期，王鼓吹与江派“和谐”，使胡温时期一直延续江时王的路线。而后亦只小学水平虚荣且蠢的习近平上台，给王沪宁更大机会公开大倒退。共党现在主要有三派,一是新组滥竽充数的习派，一是江派,另是团派。在大野心家王沪宁心中，江派和团派现没有接班的可能，习派和习的根基太子党也竟然被王政治边缘化。中共政权若没因党外而崩溃，党内只有去习才能大权变更完成王的野心。习近平若突发事件中学毛邓江镇压而双手沾血，必定会走到尽头。党内能收拾残局的只有三朝不倒的王沪宁，江派和团派都不会让对方取代习，一惯突显八面玲珑“不结帮派”的“变色龙”王沪宁渔翁得利。因此，重大突发事件如港“反送中”和大陆民众的抗争正是王沪宁学毛唯恐天下不乱而冒尖的机会，必定暗使习近平沾血镇压走向“自杀”，施计取而代之。不能的话，其极左路线被揭穿和挫败后，特别是朝鲜恼火他的教唆而使他失去唯一危机外逃地之后，这“变色龙”今后可能急变脸右转，甚至学普金窃取倒共成果，王除此绝无其他任何机会。

王沪宁还策划帮助朝鲜核导实现拥核，多次金王密谈而毁川金会谈使朝鲜上当而一度疏远中共。王还多次与塔利班等国际恐怖组织密谈，中共是苏垮台后全球最大恐怖组织，种种事实证明名“无”其实的全球恐怖组织的幕后总后台，是三朝罪恶元凶中共谍报机关及决策机构中共政研室掌门王沪宁。为什么美国几十年未剿尽小小塔利班残余，我断言他们常躲与阿接壤的中国境内。塔利班和朝鲜是最合王沪宁极左专制恐怖口味的。还策划资助委瑞内拉劝说古巴企图策划全球反美阵容，策划“新共产国际大会”和马毛邪教传播输出及习独裁的“中国梦”。策划修宪破除邓后的接班制全面回归红色独裁专制，策划一带一路浮夸“国造2025”吹嘘“厉害我的国”。中共政策研究室根据情报分析制定决策，要赶上美国唯有扩大黑客网军抢窃美尖端技术，实施千人计划和留学生情报队伍，及逼迫外企尖端技术转让。甚至疯狂到超文革，红色教育从幼儿园娃娃抓起并渗透香港教育，妄想红色王朝在国际上领先崛起。策划破坏美中贸易谈判, 鼓吹新“长征”还要求用学习毛泽东著作与美打贸易战。引来美方冻结贪官境外资产断了外逃路，摆出与美国“决一死战”姿态，策划严控网络严管民众回归毛时的闭关锁国过紧日子的红色恐怖。破坏邓小平的香港“一国两制”扶持傀儡港首泡制恶法，日本G20前习一出国王令党媒大反美。“送中”恶法出笼正是针对习玩女人一书抓港人“合法”化的高极黑做法，习玩女人一书立即炒热。一来搞臭习近平，二来逼习反美极左转至悬岩边，G20时习无法起程无法与美及国际社会和解。王沪宁还策划制定武统台湾的與论准备和决策计划等等，愚弄引诱习做统领全球极左命运共同体的“世界领袖”。王罪大恶极与毛邓江李有一拼，有些没头脑的人易被隐谋多年的王沪宁那“夹着尾巴做人”所蒙蔽，这足以证明王水平文化和人格低劣，将低俗戏言捧作“座右铭”，王沪宁承认有见不得人的尾巴而要夹着是不让人给揪着踩到，他这水平文化也不可能写出虽荒谬较系统的“三个代表”“科学发展观”“习思想”之类，这都是政研室谋士们之作。。

当务之急是全国上下并促共党内部一起欣起捣王高潮，彻底打倒王沪宁，清算其历经三朝的罪恶。王沪宁愚弄习助长毛派，倒了江派团派和邓家，也捣了习的根基太子党，内外树敌公愤极大下场必定最惨。毛泽东死前没有遭清算是中共还未倒，但在最后一次新冷战的决战中王一定会最惨！美国应对全球恐怖国际总后台王沪宁制裁和通辑， 操纵习近平的三朝罪恶元凶王沪宁不倒，不仅中国大陆无宁日，世界也面临中共新法西斯的威胁！(详请搜索郝雪森2019.6.12

== 【22】习近平咋怕民主制而川普怎称他好友

习小学毕业文革保送的"工农兵大学生"和在职读的"马列博士"全是假的,他读秘书讲稿几十年,常用词"衷心""体系""难民"等已读万遍还记不住须注音于稿。可见他学识智商和能力极差神智病态,离开注音讲稿无法作报告。习如毛也从不即兴答记者问,更无法参于竞选辩论之类事,故他最怕民主制及媒体开放等,怕露馅淘汰下台。习和他父亲深受毛独裁制迫害,其父被毛整了16年险些送命。习文革时仅13岁就被关押批斗,饿逃回家求母做饭,其母却出去举报,惨不忍睹。蠢人高抬更虚荣,黑心下作乃本性,习思想被王沪宁愚弄向文革倒退,等同清算习父开创的改革开放,低级红里高级黑。川普咋总是说习是好友？因为习曾去过美国,好色私通美女间谍并签署加入特务代号为X53,这段大陆老大详细历史,美情报局绝对不会对总统隐瞞。有了这把柄,习怎可能拒绝川普为好友？或至少是道合仅志不同？川普总爱说的"好友"竟有如此惊世来由意味深长。也正因此,习夹在川普与三朝罪恶元凶全球恐怖国际总后台王沪宁之间,内外交困,左右为难,晕头转向,神志失常,命难长矣(祥请搜索:郝雪森6.29

== 【21】川普若与习签约落陷阱不挽救则连任无望

香港恶法百万游行震惊世界,而中共仍未表中止恶法；仍未停反美宣传,毫不中止三朝罪恶元凶全球恐怖国际总后台王沪宁极左路线。中共急签约是为缓解内外交困处境,中共无守约习惯和记录。我预言中共连按会谈或协议原意以中文公布的最起码作法也不会有,别想会悔改,王沪宁使习挫败刘鹤而仍让刘主谈明摆是先签约再次计划毁约,使川普难连任助拜登上台望转机。美所有让步必履行,而中共绝不会履行承诺还得以喘息,川普易落陷阱告败投降。

中共为达目的不择手段,腐蚀是中共一惯很见效的手段,我预言习会给川普或要员家族企业利益等礼品,话说也不会留证据何不一试？我断言会谈或签约后中共官媒会宣告胜利,极左倒退乘机造势,那还有改的空间？！中共若真想改邪归正,先答应两点足已：一是拆除网络防火墙通讯畅有利自由贸易：二是双方零关税有利两国人民,这是自由贸易最起码的保证,我预言中方连写入协议纸上也不会。打两年多贸易战若中方无任何改变川普定无法赢得连任。挽救的方法是立即计划就中共必然的毫无改过或必定违约,贸易战逐步升级彻底打垮中共,川普才能连任(祥请搜索:郝雪森

== 【20】要求政府就两个问题向美国人民和国会作以检讨

世界和平危害最大的中共大独裁者习近平的女儿在美国读书几年里,据悉美国政府用我们纳税人的钱派员长期保护她。她和所有外国学生一样是自愿来学,不是来访贵宾为什么要长期保护?我们是一个人生来不平等的特权社会?!对中方高官家属是否有种种名目助纣为虐的优待?如何取消他们几乎人人都有的绿卡和如何实施遣返?习家人定为习女等办好外逃资金和绿卡,针对三朝罪恶元凶王沪宁和习近平与江李等家族,政府必须全面检讨解释和道歉。

第二,《全球马格尼茨基人权问责法》对犯有侵害人权或贪腐的外国官员可以实施冻结其在美资产等制裁,。由于中共历届高官及家属把持大陆经济命脉贪腐世人皆知,违反美国对几国制裁的也是他们的私家公司,其侵犯人权更是世界之最。政府下步落实上述问责法条款有无计划和行动是否冻结他们的非法所得资产？我呼吁有知情权的国会社会各届和国民,敦促政府就这两个问题作以表态解释和制定纠错计划,如颁布"中共官员腐败和侵犯人权的问责规定"。因为这些是为了世界和平,能给中共内乱升级而解体的最致命打击的关键策略,将利于终结共产邪恶,建立世界和平新秩序从而载入史册。(郝雪森

== 【19】短评一，刘昕仕途暗淡

从刘昕几天停职准备和中宣部外交部及官媒造势来看，中美主播辩论原是要直播的，忽然改为对话并不直播很可能是刘夫妇的原因，刘的德国丈夫若为孩子考虑也不希望为明知的没落政权如此大露锋芒。所以刘昕一开口就否认是中共党员声明不为中共说话，刘仕途若此后而止将佐证这点。(郝雪森

二，大陆测试题：

试试你能在几秒内数清下图有几根：

ííííííìíìíìííììììíììíììíìììíìíììììíííìíìíìííììììíììíììíìììíìíììì

方法一：用几秒钟粗略数后识图和联想;

方法二：数上部尖头结束后以你的智商判断验算。

答案：图为64根蜡烛 （大陆请别转贴答案）

郝雪森原创2019.6.4

(详请搜索郝雪森

== 【18】纪念六四大陆全国"六月飞雪"活动倡议书

我在大陆时有一邻居每年6月4日晚会在窗口点燃一烛,后来才知道是纪念6.4。出国后发现只有国外有纪念6.4活动,国内却无法纪念。今晨我想到大陆纪念6.4的全国"6月飞雪"活动：将白纸裁成64开,约为9.X12厘米(16开普通稿纸裁4张),今年是30周年一次用30来张,六月四日从楼口或行驰的公交车上或无监控头的任何地方抛出,在高楼层抛更好,形成"6月飞雪"景象。一年任何时间地点都可抛!使小纸64开与6.4形成全民常态联想,逐步扩大大陆纪念规模,还可打印64开的6.4屠杀图片或文字。

同情6.4学运的大陆同胞们,现在就开始,在全国任何地方飘起"六月飞雪"!请帮转发(详请搜索郝雪森

== 【17】给习总女儿习明泽的公开信

习明泽小姐:你比谁都清楚你父亲的学识和能力,能影响他决策的只有他身边的人和你。他目前学毛极左独裁,一定是听信了王沪宁。但唯有你会真心为你父亲考虑,你在美国多年,传说你现在就在美国学习。应该明确主政者选择民主或独裁的区别和最终命运,这不仅对你父亲和家庭很重要,而且对我们的祖国乃至全世界也极为重要。你父亲被王沪宁等弄得焦头烂额,精神压力极大,发展下去很危险,要让你父亲解脱唯有顺世潮随民意。身为党魁要放弃这独裁的党政虽不容易,但这也是转变后能让世人原谅的理由。要回头先要严惩三朝罪恶元凶王沪宁,重新回归你祖父开启的改革开放,全面政治体制改革,融入世界文明民主社会,这才可留名青史。

若知错不改你父亲必是屈指可数的历史罪人,想必你不希望如此。你父亲身边的人与你的想法就一定不同,因为你应该不会有他们那般巨大的权力欲望。然而能让你父亲清醒的只有你,你在他心中的份量应该是他人无法相比。你最可能使你父亲转变,告诉你父亲,他不转变你就不回国或不回家。找个地方躲起来,党魁女儿申请政治庇护出个世界奇闻也未尝不可,也可载入史册。如果你不这样会后悔一辈子,不信,也不容等着瞧!(郝雪森

== 【16】若用这三张王牌中共必垮川普成为终结共产邪恶的英雄必赢得连任

王沪宁愚弄习近平学毛极左倒退,使中共面临全面崩溃边缘。若川普用以下三张王牌施压,中共绝对熬不过两年而垮台。

首先是贸易战要尽快升级,与中共谈判别抱丝毫幻想,中共从不可信,只有以失信违约尽快升级制裁甚至加以40%关税,让中共先经济快速崩溃；第二是多渠道促其社会动荡,频繁暴发较大规模的民众抗争；第三是最致命的大王牌,即挑起中共内斗加剧升级,中共高官普遍贪腐且绝大部分资产已转国外,这大王牌是尽快启动对中共贪腐高官境外资产的冻结。先选择几员开刀即可震撼整个贪腐的高层,内斗必升级加速崩溃,会非常见效。最好在习家族、极左的王栗家属和江李红色权贵中,选几员冻结其境外资产,中共内部必大乱而崩溃。美方制裁的几个国家得到中共暗助的主要是这些权贵家族公司,以此为由对其海外资产冻结顺理成章。

若川普让步或达成缓解协议,让中共喘息而又未解决不公平贸易,对川普明年11月竞选连任极为不利。只有利用贸易战升级、促使大陆动荡及内斗加剧中共迅速垮台,美国和盟友打赢终结共产主义邪恶的冷战,川普便成为英雄载入史册,连任必成定局（祥请搜索:郝雪森

== 【15】王沪宁如此策划令习近平再活不过两年

习实是小学毕业保送工农兵"大学"坐飞机,比毛泽东初中肆业还差。故毛习都不敢临场答记者问,离秘书稿讲话必出错。王愚弄习学毛一明显不同的是,毛很少公开露面,无紧张的精神压力,故活过80岁,文明国家换届也为免于过重精神压力。但三朝罪恶策划元凶王沪宁,令习频繁开会出访开会讲话,与毛的精神压力大不相同。最近传出的习讲稿可看出,习有持续严重精神恐慌。习从政讲话几十年,连讲稿常用词"谨向"'"衷心""会晤"""体系""难民"等小学生大都认识的字,已读几万遍还记不住须注音于稿。有人难信认为高级黑,我说习已有持续严重的精神恐慌病态心理。习这几年衰老很快,面黄暗无血色,白发甚多。也许是其女的"形象"策划,近年渐露少许白发作假使人心理感觉"真实"。

王若再策"习思想"古今中外一绝出口乃名言,加重习精神压力,预言年近七十的习熬不过两年随时随地粹死。王策划修宪旨在不明确安排习的接班人,习死后常委中可能掌大权的是王。王久谋从不入帮派三朝不倒都易接收,但江派和团派都绝不会让对方主政。王筹谋几十年的野心可能实现,除了习死乱局中高人涌现,激民起思变而走向民主。（祥请搜索:郝雪森

== 【14】美中贸易战谁胜谁负,只需看中共是否仍然推行王沪宁极左路线

美中贸易谈判过程中和履行协议期间,中共不肃清而是仍然推行王沪宁学毛文革极左路线 ,这时与之达成协议而不是加紧惩罚中共则是最大失败。美方要求中方结构性改革,中方只是书面承诺却行动仍向极左倒退,达成这种协议美方就是投降。

中共三朝罪恶元凶王沪宁一惯极左仇美,中共若不肃清其路线,倒退拒绝政改,继续内外号召反美,支持反美国家,打击西方民主自由世界,企图一路称霸世界,是极端危险的。中共从不循规蹈矩 ,有极左的中共世界必乱无经济秩序可言。眼下只需看中共是否有意釆纳其党内"平反六四"的意见,对六四学运人士的打压是否加剧,就可看出中共有无改的诚意。

面对倒退的中共,美国和西方世界唯有团结一致对付它。除了大陆不断暴发突发事件危急中共,外部世界只有在经济上施压能起作用,如果这一点也放弃,绝无胜算可言。是考验川普有无里根的政治远见智慧和魄力的时候,也是能造就人类终结共产邪恶的世纪英雄之时刻。在此贸易战掀起意识形态冷战的关键时刻,希望川普留名于史的是一代伟大的政治家,而不是只图眼前商场利益而有幸官场一游的商人。祥请搜索: 郝雪森

== 【13】大陆军民今年要特别严防流血事件发生

已是大陆政局最动荡的时期,很可能发生重大突发事件.当下王沪宁愚弄习近平学毛独裁已接近文革式恐怖状态,一旦发生重大突发事件,王必定会学毛暗使习血腥镇压以防苏式崩溃.共党目前政治格局.内斗主要有三派,一是新组习派,一是江派,另是团派.隐谋多年的大野心家王沪宁心中,江派和团派现没有接班的可能,习的根基太子党也竟然被王政治边缘化.中共政权若不因党外而崩溃,党内只有去习才能政变.习若突发事件学毛镇压双手沾血,必定会走到尽头.党内能收拾残局的只有三朝不倒的王沪宁,江派和团派都不会让对方取代习,一惯突现八面玲珑"不结帮派"的王渔翁得利.重大突发事件正是王沪宁学毛唯恐天下不乱而冒尖的机会,必定暗使习近平沾血镇压走向"自杀",施计取而代之,王除此绝无其他任何机会.

大陆同胞一定要防范"六四"等大流血事件重演,关注三朝罪恶元凶幕后最有实权的王沪宁,广告天下揭穿其阴谋.请大家转发告知共军官兵们:共军绝大多数来自平民,在被派处理突发事件时,宁可向老天爷开枪,也绝不能向同胞父老兄弟姐妹们开枪!!离中南海近的可调转枪口. 祥请搜索: 郝雪森

== 【12】已到中国变革复兴最佳时期,合力打倒三朝最恶元凶王沪宁!

三朝罪恶元凶王沪宁一惯极左,其受益于小学肆学却因文革政治需要保送外语班而翻身和其父的马毛灌输,一生堕入马毛伪政治学仕途偏门.苏亡江恐理论危机,看上王聚谋士赶编的强权独裁谬论,左转被邓南巡阻止,王策江应合邓搞经改却停政改.阻止平反64,镇压法轮功,抗美军援前南斯拉夫核助朝鲜财输委内瑞拉,胡上台王吹和谐延续江时王路线.亦小学水平虚荣且蠢的习上台给王更大机会,大倒退修宪仿毛独裁,全面根固文革式马毛邪教,浮夸一带一路国造2025,金王多次密谈想扭转川金会谈等挑起与美冷战,王豪赌是自杀并断送中共,还除最后障碍习的根基太子党,习蠢到倒退打父脸,挣眼看王挖坑埋自己.王极左习与美打贸易战,使全球反共反谍反洗钱连带发酵,断送官员携家逃境外的后路,老百姓与各帮派官员都成了王极左倒退的人质.王要实现其隐谋多年的野心,唯有操控更庸的习傀儡学毛专横独裁,不惜让全国上下过苦日子.除习，几乎所有人都明白.( 中共必诱以川普家业和连任需要,但从不履行协议,必应借违约逐步打死中共,中共危境被动不会撕毁协议也无能报复,中共不亡必严重祸害全世界!祥请搜索:郝雪森

== 【11】打倒中共幕后操手王沪宁,六四和法轮功事件才有望翻案,朝核问题才有望解决

镇压法轮功和最终为六四定调阻止翻案及处理朝核危害世界和平等重大问题,表面上是江泽民及其后两继任,而实际上起决定性作用是深藏幕后的王沪宁!

中共自六四政治危机和前苏东欧垮台的信仰危机后,江泽民等中共领导人全靠王沪宁的诡辩“理论”撑门面维持一直动荡的政局,法轮功并没有把矛头指向江泽民等中共领导人.中共领导人都是没经竞选的众所周知的庸人,特别是习近平,竟然是没念过初高中的小学毕业生，文革上的工农兵大学和在职校外马列法学博士更是极假.江泽民等中共领导人之所以会用残酷镇压手段,实际上是听信了中共政策研究室王沪宁对政治的分析后,幕后操作江泽民等对法轮功和六四事件延续三届二十余年的定调和阻止翻案,及在朝核问题都是耍王沪宁阴阳两面法,并正在逐步倒退至去毛臭标签的文革意识形态.这是显而易见的事实!只有先彻底揭露和打倒中共幕后操手王沪宁,六四和法轮功事件才有望翻案,朝核问题才有望解决,大陆才可能前进. 2018年1月2日

== 【10】告全国同胞书和致中共汪洋李克强等高官的公开信

全国同胞们、汪洋李克强等中共高官们:

美国总统川普以贸易战的方式打响了终结邪恶的共产主义的冷战，中国人民真正解放的日子不远了。中共内外交困危机四起崩溃已是必然。别指望糊涂虚荣且真正只受过小学教育的习近平，他在王沪宁之类极左们的愚弄下，只会祸国殃民加速中共的灭亡。

中共正处崩溃前的苏联状态，有过之而无不及，这更倍增川普成为终结共产主义英雄的信心和决心。

此关键时刻，每个中国人必须行动起来! 大造舆论，制造或寻找并参与终结中共的每一件力所能及的大事或小事，摧毁中共，复兴发展中西结合五权分立统一的中华民国。

为顺利和平演变避免动乱降低社会成本，能出叶利钦式人物较为理想。望有良知的汪洋李克强等中共高官们，是你们作出选择立即行动的时候了，机不可失。你们有川普同样的，成为终结共产主义的英雄载入史册的机会。此刻对中共党员特别是高官来说，没行动就是等受谴责或审判，会殃及家庭务必三思。

同胞们，为了我们和子孙后代，以行动复兴发展统一的中华民国！

签名:郝雪森

（请搜索本文在签名最多的网页都签上名后多转发）

== 【9】中国新党筹建公告

中华民族正处重大关头,大陆复兴中华民国的机遇来临,我们筹建“中国新议政党”简称"中国新党"。

中国新党的宗旨是创建中华民族的新型社会模式造福人民,为国际大家庭树立典范。

现行目标是在大陆复兴中华民国并筹划两岸统一,重树和发展孙中山先生的"三民主义"和"五权分立"中西结合的社会模式;敦促习近平放弃马列邪教,促其宣布解散或更名重组其党和宣布开放党禁报禁履行言论自由等,促其在大陆恢复中华民国。在此前提下,我们呼吁海内外中华儿女及各社团组织,在大陆和平过渡期,接受习近平为大陆新复兴的"中华民国"临时大总统,直至一两年内全国大选。先行议会选举和新宪法的完善,及大选的筹备。

在互联网信息社会中,我党暂行在网上任何网页或社交媒体或电邮声明入党并有姓名日期截图依据的申请方式,为以后初审颁发党员证用。待于大陆正式建党后,所有连带累计顶层达界定人数的介绍人,通过初审入党后为首届党代会代表。

我党的方向和发展等议题事项有待您的加入、参与、组织和贡献,同时广招栋梁之才。

将不从政不参与候选的创始人:郝雪森 2018.7.30. haoxuesen@gmx.com(请转发,或区块链



== 【8】 王沪宁愚弄习近平大倒退与美冷战必断送中共

习近平承诺大开放,若真再开放将一发不可收拾,结局必是中共垮台.若不让步开放贸易战必导致中共经济崩溃更快垮台.海南建自由贸易港是再开放的假门面缓冲地,更是权贵敛财新特色特区,内大陆不会再开放.

操纵甚至可说愚弄习近平的王沪宁等人,己习惯使习不顾颜面左右摇摆,颠三倒四.让步是缓兵之计,边拖边看,假改逼到危急中共生存再变卦.王沪宁一惯疯左,阻止平反64,镇压法轮功,军援前南斯拉夫,核助朝鲜,促成既得利益集团,大倒退乃至修宪巩固独裁专制全面根固文革毛式马列邪教,一带一路扩张,中国制造2025,金王密谈想扭转川金会谈等与美冷战,所有极左策略操手是王沪宁!他是在自杀和断送中共,并捣最后政敌习根基太子党,习蠢到挣眼看王挖坑埋自己!(我2016年始发9篇揭王文章于大陆内外全网散发两年,是全网全国捣王撼陆第一人,祥请搜索:郝雪森

== 【7】 王沪宁加快倒退愚弄习近平走毛独裁路,决心与美冷战妄想成为世界霸主

我有文章分析过,王操纵江泽民欺骗胡锦涛玩弄习近平是中共幕后最有实权的人.升常委后以完成"习思想"加紧愚弄习,舍弃部分职位继续掌控政研室.

王90年代初以其萌芽的毛式独裁新权威政治之说被江泽民看中求教,江本无主见.邓小平南巡阻止了江倒退,江为太上皇的胡温十年也没如愿倒退.习上台后,王很清楚习本性虚荣愚笨且实际只受过小学教育,易愚弄,以完成"习思想"左右习倒退走毛独裁路.与朝鲜和解则更是决心冒与美冷战之险,朝鲜不会真正弃核,与中共和解是为确保这点.除了美让步或战争解决.实际形成新冷战,迫使美国要解决朝核之险必先要如苏联崩溃一样,以中美经济之战使中共垮台,朝鲜无助也迅速崩溃,无须热战.

王左右习以巨资向西方世界输出其意识形态并扩张势力,愚弄习为世界领袖做妄想主宰世界的"中国梦".王受益于毛文革上工农兵大学而升迁,他善变善于伪装,根基极左.但没善恶对错标准,可变任何左或右形态,打造不管是否有无习为傀儡的他的王国,必须广泛关注实际由他所左右的中共动向！（郝雪森

== 【6】 大陆复兴中华民国

全球华人行动起来，在国父孙中山旗织下统一中国！2018年将是中共内外交困全面走向崩溃的标志年，其唯一赖以生存的经济将面临前所未有的危机，美国减税,大陆国企重负,外企撤离,资金外流,企业倒闭引失业潮，银行负债,人民币贬值,生活水平下滑,贫富差距再增，股市楼市泡沫严重等。朝鲜一旦战争，将加重我东北朝核污染和可能更大范围生化武器污染及难民涌入，损害不亚于朝鲜。民怨加剧和中共内斗使局势更加动荡，皆极可能使中共黑暗独裁统治结束。在此中国乃至全世界的重要历史时期，全球华人行动起来，促大陆和平复兴中华民国。民国是孙中山领导人民推翻了历经数千年的封建社会而建立的丰功伟业，大陆复兴而统一的中华民国是真正超级大国。

特拟先行主张：

1，大陆现有共党及附庸党团工会等组织，只要放弃暴力恐怖的共产主义邪教条，上交全部非法党产或社团资产，其组织可存留。其在各政府机构的官员也可留用于保留机构中，前提是上缴个人非法所占资产并接受相应认证，否则依法处理。释放全部政治良心犯，在台国民党等政党社团只要没有台独等违宪主张，均可与海外民运或练功群体等在大陆发展一起参政议政。

2，大陆复兴民国后，台湾香港澳门为特别行政区，保留现西藏新疆广西宁夏等自治区，享有高度自治权，内蒙也可管辖权交外蒙统一蒙古并高度自治换其回归大中华民国，其他邻邦也可自愿效仿。保留大陆现行政区的划分和留用各专职人员，直至考试院成立。

3，为扭转大陆罕见的贫富悬殊，鉴于大陆大多数富翁和全部暴发官员及红色家族的财富是非法所得，作好全面大幅缩小贫富差距的准备。全国资产评估并以城市中层人均资产为参考定以基线，全球收缴红色家族及官员暴发户超出此基线之资产，包括银行存款和房产等，补足个人资产不足基线者，富翁超出的资产作合法认证后可保留。

4，清除毛像毛尸堂，废除人民币，换以新中华民国元。每户长期住地，是城市则分一套住房，是乡村则分一份土地，以中共解体前资料为准。取消中共户籍制等恶规恶法，优先建立落实人权和环境与食品安全监管法规。以原中华民国宪法为基础健全宪法和五权分立的民主体制。

5，全球华人开展评议备考待选的“找寻中华民国大总统”活动，无党派地区性别等限制，寻德才兼备的两对正副总统竞选伙伴，迎接大陆复兴中华民国的历史时刻！

郝雪森2017,12,30

== 【5】总结百年号召百姓：三字今(经)

我中华,数千年.饱沧桑,封建延.孙中山,有卓见.捣皇朝,民国建.倡三民,分五权.民主制,体制坚,中西合,文明兼.创伟业,非凡缘.二战起,风云变.日寇侵,亡国险.蒋介石,抗战宣.保国土,精忠献.联合国,国威显.最可恨,是苏联.割外蒙,入侵圈.扶中共.马列奠.毁中华,民熬煎.共产党,罪恶元.苏维埃,傀儡园.斯大林,干儿牵.毛泽东,大汉奸.恶流氓,最疯癫.勾日俄,内战添.假解放,真深渊.学秦皇,焚书卷.划户籍,自由限.立特权,等级严.搞运动,文革巅.毁文化,道德践.八千万,死得冤.民疾苦,崩溃沿.邓小平,救党艰.搞经济,挣了钱.红家族,全升天.暴发户,激民怨.学运起,屠城溅.胡耀邦,政改现.赵紫阳,同遭陷.六四事,转折点.苏联垮,东欧颠.此大陆,钻钱眼.江泽民,贪不厌.人活摘,死医院.聚贪官,集红眷.搞垄断,贫富悬.假反贪,腐败遍.李鹏等,红贵殿.国资产,霸占全.仅薄家,罪查检.胡温办,祭旗典.习近平,小丑演.小学生,博士惦.无知者,无畏焉.愚蠢者,被愚骗.成傀儡,太丢脸.反腐亦,政敌歼.红族贪,无一贬.学老毛,崇拜恋.想独裁,倒退原.人权丧,网络监.王沪宁,流氓颜.妓女相,专诡辩.伪政治,满邪念.在幕后,玩两面.罪难逃,骂名连.新世纪,光明艳.普世道,民主先.独裁衰,自由乾.同胞起,醒梦眠.灭红贵,抗争掀.共产除,全民愿.新民国,幸福源.民富裕,国强健.创历史.复兴篇.世界和,结局圆.（详请谷歌：郝雪森

== 【4】习近平成为多线撑傀儡的政局预测

作者：郝雪森

皆知习近平小学毕业遇文革,初高中未读却保送工农兵大学,后以红二代当官在职读马列,为"博士"太假！天资不足好虚荣,乃无知者无所畏惧,愚蠢者易被愚弄。但没人弄习就动弹不得, 操纵玩弄多线撑傀儡习的有王沪宁刘鹤等“高参”。对刘等来说弄习出成绩有利仕途,而对王来说习无成绩下台才继之有望,习受两相反作用力左右。

人大刘等或会谋以总统制作政改秀,震动大定位可不明确,但习留任王就没戏。学毛独裁完成"习思想"是王操纵习的关键,刘父死于文革恨毛会想修宪去毛化。修宪和政策会是妥协结果,或学普京总统制和军队国家化,习还是独裁傀儡。或宪法删些过左修辞,但实质反西方。总统制更可弱化李克强等非习家常委。学毛独裁搞个人崇拜习必遭骂名而下台,王沪宁乘机收拾残局,婊子立牌坊是他的无对错求实用的特色政治。左右习的王栗赵刘丁陈等“高参”习家军都60多岁,不搞总统制按旧规,要高升延续政治生命难。

修宪或去人名或留一句"马克思列宁主义毛泽东邓小平习近平三时期中国特色社会主义思想",还可改的是每届人大是在党代会半年后召开,期间有多部门半瘫痪。

== 【3】 若有下届则19大最大赢家王沪宁任总书记可能性最大

作者：郝雪森

我发表在北京之春网三篇之一《操纵江泽民欺骗胡锦涛玩弄习近平的王沪宁是在幕后最有实权的人》中揭示和预言,原入常呼声高的王沪宁令主要官网只删除其一人的简历资料,做出局假相躲避了王歧山栗战书被暴丑闻众矢之的局面,19大再杀回马枪。

这黑马王沪宁是最大赢家:1,成功入常.2,让习揽大权但没当党主席,习若当党主席20大必连任,王沪宁没戏.3,常委中无60后接习的班,20大能留任的常委排前列的又能使习和多数所接受的只有他.4,常委留三大派易树敌约束习,习的铁杆仅栗一人比预想的少,习难摆脱他.5,他最不愿废除且没废除七上八下,习想再连任仍多此约束.6,他新职曾是中共接班前的常务书记党校校长和政治思想與论等其20余年的强项领域.这对他最有利的至少6点绝非巧合,幕后就是他！

他不在乎江胡习史上留什么名,可能不会自己留骂名.形势所逼他或许顺世潮起动政改,至少学普京的总统制.下一步或许会令习稳大权却无须有成就,给习树敌而已中立,掌控政局.习思想已离不开他,诱习利令痴昏（没智）学毛个人崇拜,再五年笑柄闹剧下台,习近平的确是无知者无所畏惧,愚蠢者易被愚弄.

== 【2】 操纵江泽民欺骗胡锦涛玩弄习近平的王沪宁是在幕后最有实权的人

作者：郝雪森

{blank}[我去年开学时写了《这位可敬的老奶奶教子可谓名留青史》（习母教训习近平的电话被窃听內容）一文发表在“北京之春”网站后，开始对中共政坛及其动态感兴趣，一年里我用了大部分学余时间进行收集和分析，感觉有必要写点，以揭示中共政坛真相特色]

在古今中外史无前例最大历史罪人毛泽东发动文革浩刧使中共动荡衰退之后，经邓小平仿西经济改革的挽救，逃脱了苏联东欧式的崩溃。但在中共首要的思想政治和路线上，面临“姓社姓资”的争论和危机，也是那六四天安门大屠杀之后上台的江泽民面前的最大难题，摆在中共中央政策研究室政治组王沪宁桌面上，使王沪宁有了对此后中共几届都无法摆脱的实质性的幕后掌控权。中共政治的特色，由黑厢操作私下交易产生的并非人才，所以真正实权操纵在幕后的秘书，特别是政治“智襄”手中。

王沪宁何许人也？他和习近平一路人相同，文革开始时是念小学或刚进初中就停学去“闹革命”的，初中高中均未读却受益于毛泽东文革而逐步青云直上彻底改变了命运的人。有的被保送上“工农兵大学”?有的经文革后超低水平的“高考”进入大学。这类“工农兵大学生”毕业后绝大多数不能真正从事所学专业，也因此有不少人如同习近平投机改行。但大陆“政治系”专业除外，大陆所学马列政治专业的人在绝大多数国家或文明发达国家是无法找到对口工作必定改行的，唯独在大陆却是重用的紧缺“人才”，中共信仰大危机后更是最重用的救党“人才”。这也就是像王沪宁此类“大学生”平步青云的原因，他们最熟悉毛泽东历次运动的宫庭内斗经验，和手段残酷的阶级斗争暴力夺权的“政治学”。要提示一下，如上所述王沪宁此类水平也能平步青云是靠他的中共马列“政治学”资本和头衔，不是什么了不起的真才实学，能干实事有点真才实学的或许在他手下秘书班子中可以找到。王沪宁的“真才实学”不过是一个只读四年小学的人，大半辈子在社会上磨炼在中共宐场滚打的手段和经验而已（仅这点和王岐山相似）。王沪宁可能至今还不知几何代数物理化学等最初级最基本的概念，也没听过初中语文老师讲课。他们是在毛泽东文革时期受宠的最大受益者，是中共少有的有真正“红色基因”而又有变色龙双重特色的人。

王沪宁是中共自邓小平死后至今，制定中共思想理论政治路线重大决策的人。从1997年邓小平死后三个月他参与撰写江泽民5.29重要讲话开始，他就以不左不右为幌子，策划只搞经济改革，不搞政治体制改革的方针路线，在他为邓之后的江泽民胡锦涛和习近平制定的纲领“三个代表”“科学发展观”和“中国梦“等等之中，只字不提政治体制改革。而实这二十来年也未作丝毫政治体制改革，相反却一步步向毛极左方向倒退。

王沪宁为江泽民提供了“三个代表”一说，从而在政治思想和路线决策上操控江泽民，成?江不得不依赖的首席“智襄”，为江泽民出谋划策，打击党內政敌，以腐败引诱和网罗红色资本家各红色家族形成宠大的既得利益集团，垄断大陆各大经济命脉，全大陆贪污腐败疯行，把持政坛祸国殃民一二十年。

胡锦涛上台后，王沪宁仍是无法摆脱的首席“智襄”。他又以“科学发展观”装饰门面，由他诱骗而江泽民团伙则威逼，使胡锦涛听从他的“和谐”主张，接受江派大员和既得利益集团胡作非为，延续江派的政治路线，进一步扩大各红色家族的经济侵吞垄断，使人民生存环境严重恶化。

等到习近平上台之后，王沪宁更是将习玩于股掌之中，引入昏梦境地，令其独揽全部大权，也不顾及前台的习近平言行前后矛盾，左右摇摆，举国上下对立，内忧外患。利用反腐打击异己和党内政敌，那些巨贪的党内几个大佬和一大堆红色家族暴发户一个也没抓，打倒的唯一一个红二代薄熙来还是在胡温手上抓的。王沪宁利用习近平的无知愚笨和虚荣心，利令痴昏（没智）学毛搞个人崇拜，逆民意反世潮搞倒退，明显致使习近平给跟随胡耀邦赵紫阳创立改革路线的其父亲习仲勋一记响亮的耳光。 由此可见习近平的确是无知者无所畏惧，愚蠢者易被愚弄。

王沪宁就是如此尽情如意地玩弄习近平，举最近一例，前不久川普第一次参加的联合国大会，本应是习近平最想以世界另一老大身份参加的。但是，习如果去参加联大，王沪宁若照惯例随行，必会如同栗战书一样成为十九大前的暴料焦点众矢之的，若不随行，则必会误为失宠而与进入常委或攀高位无缘，故其令习没去参加联合国大会。对栗战书来说随习参加联大则是有利消除暴料丑闻影响巩固地位的机会，王沪宁则不想要习参加联大所以没去。王沪宁前段时期的入常呼声很高，但在北戴河聚会和王歧山栗战书被暴料之后立即转为低调，就是为躲避锋芒，19大再杀回马枪。再举一例，胡锦涛18大裸退，习近平当时感动得几乎落下眼泪。可是，王沪宁这四五年，教唆习除了打击年老的江派人员，疾尽全力打击“少壮”的胡锦涛的团派大员。若有人问王沪宁为什么恩将仇报，他会说，胡对习有恩可不是对我王沪宁有恩，团派人都上去了我怎么办？所以有说胡锦涛提出党章去掉“三个代表”和“科学发展观”，一是打击王沪宁，二是暗地阻止19大党章写入习的啥东东。

王沪宁在这二十余年幕后低调干政，隐藏着他的一大阴谋，就是只有让习近平当傀儡在前台尽力独揽大权，学毛泽东说一不二后，他才能台后操纵实现他的最终目标。若习近平十九大人事按排受阻不能如愿以偿，王沪宁也就基本上玩完了。

王沪宁一个高小肆业生竟是中共二十余年来幕后真正最有实权的人，也许有人不信。但是，想想中共党魁习近平，连他也实际上只是一个小学毕业生，这又如何解释呢？这就是中共由毛泽东建立的用人特色。毛泽东学秦始皇焚书坑儒, 重用无才无能但很听话的奴才。只不过，若说的好听，王沪宁很像王岐山比习近平江泽民等机灵得多，说的不好听，王沪宁比习近平江泽民等老练狡猾得多。所以中共历史上高层腐败分子政治流氓低庸之辈层出不穷，祸国殃民至今依然，中共倒台绝对为期不远了。 2017.10.16

== 【1】 这位可敬的老奶奶教子可谓名留青史

郝雪森

----讲讲我哥第一次做小偷时听到总书记的母亲电话教训总书记的话

这次署假回家，哥哥酒后告诉我一个惊人的秘密。前几个月，他得知母亲病危准备赶回家，在他打工的城市的火车站，发现钱被偷了. 为母亲筹到的医疗费全完了，哥心急如焚。返回打工住地时，哥遇上女同事的一个亲人，想到此人是在一家很富贵的夫人家做工，便起了歹念。哥跟踪此人来到了那富贵的夫人家院门外，计划深夜偷窃钱物。等到晚上十点左右时，忽然下起大暴雨，哥乘机跳进大院，并爬上了紧靠二搂一有亮灯的窗户的一棵茂密大树。不久室内电话铃声响了，哥看到一老奶奶开始通话:

“......，你爸不在了，我就每次都要反复提醒你，你身为总书记一国之主，你的责任太大！......”，哥听到这句后，吓了一大跳，想走，可又不敢动，好象一下去就会有人抓住他. 他畏缩在茂密的枝叶中，最后决定等下一阵雷雨时逃走。此时，他还能清楚地听到那老奶奶的训话:

“我不想听你的辩解！有不少你爸的老部下向我暗示，你和你爸走的不是一条路。我告诉你，你要倒退,与你爸创建的改革道路背道而驰，我决不答应！”

“你可能意识不到问题的实质和严重性，这里没别人，我要用'冷水'泼醒你！我做母亲的，最清楚你们几姐弟中，谁读书好，谁的水平能耐如何。这些你也应该有自知之明, 再加上你其实只有小学文凭, 你的能耐就一清二楚众所周知了。你刚进初一就文革停学，初中高中都没学过。后来保送清华上大学， 都知道那是可交白卷只是为了镀金的文凭。再后来你又当官在职读啥马列博士，国人谁会不知道这是假文凭？一个没啥能耐智慧且只念过小学只学过小学语文的人，管理这么大的国家, 你能离得开秘书半步？你完全被你周围的人利用和摆布，背离了你的父亲还蒙在鼓里, 你是活在他们编织的梦里！”老奶奶的这番话说的很激动也很不客气。

我哥虽是打工仔,可也有作为一个大专毕业生对时政应有的理解, 他心想，东西是不能去偷，但能偷听到如此“国家大事”，没有白冒险一回，哥似乎是屏住呼吸倾听着:

“想倒退到那文革浩"o的毛时代？忘了你和你父亲打成'反革命'被揪斗的那些年？忘了你爸被迫退下后对你们反复交代的话？你糊涂啊，太糊涂！我反复说过，你只有用对人也许名留青史，你若用错人就会遗臭万年，毁了你爸的名声！我死了也不瞑目”。

“你爸有过两次只向我一人暴露过内心深处的真实思想，第一次是四人帮倒台后你爸被平反恢复工作时. 他说解放后二十多年里，毛泽东学斯大林给人民带来古今中外前所未有的苦难和浩劫. 毛所建立的体制必须改革，所以你爸在深圳搞了中国第一个改革试点。第二次是六四镇压学运以及苏联东欧共产党纷纷倒台后，你爸被迫退下时，他说中国迟早也会有苏联和东欧同样的结局. 要你们姐弟们远离政治，最好远离大陆，而你却没有做到。不过，你爸也理解你的苦衷，你四年工农兵大学是坐飞机只学了些马列毛思想，你无法从事所学化工专业。你也去过国外试了一段时期，体面的工作一件也干不了，不体面的工作你又不会去做. 工农兵大学除了学会26个英文字母，你也不认识几个英文单词。这也是你不能随前妻出国而离婚的原因之一，你只有留国内从政，有红二代金牌撑着，你爸理解你的这种无奈处境。但是他留给我的遗言反复强调要我常常提醒你: 在这个体制内当官要牢牢记住, 1, 只能做改革派; 2,只能顺世潮顺民意做对民众有益的亊. 只有这样今后才可能不被清算，你爸临终时也只对你这件事很不放心”。

“你身边周围那几个人，若不是只会阿谀奉承的小丑，就是很有心计的野心家，你就是被他们这些'高参'左右摆布。所以让国人越来越对你失望, 如此再进一步便是祸国殃民, 你必定遗臭万年，你周围的'高参'一个也逃不了，必遭严惩! 你职位最高，因此今后最大的野心家也只能出在你身边。他们只有让你学毛搞假民主只集中，独断独行，他们才有破格出头的机会，种种的违规破格打破格局对他们高升是必要的，对你就没有必要却有很大的风险，他们也不会顾及你留下骂名。”

“现在是最关键的时期! 要么学你父亲, 像个真正的男子汉, 大胆改革, 失败了也问心无愧。不行，回不了头就给我辞职. 你别无选择! 让别人或老百姓赶下台那就晚了，不仅会留下骂名，还可能落个前罗马尼亚的齐奥塞斯库的下场！一想到这点，我这做母亲的天天都无法安心。”

“和你讲的这些，也许是我一生留给你的最后的心里话，可以留给今后来证明. 智慧对任何人无论对庸人或能人来说都是有限的，能倾听大多数人的意见则是最大的智慧，对你来说是要多思而后行！”

{blank}......

大概半个小时后，又一阵雷雨狂下，哥赶紧爬下树来翻墙逃脱。

以上老奶奶的话，只是她反复强调和给我哥印象深刻的几句，半个来小时老奶奶反复严厉教训了许多，主要还是围绕这些内容。

原本我不愿写下哥哥这企图行窃之事，但是，一想到老奶奶忧国忧民，如此正直可敬的品德，我决定公之于众，更值得新时代年轻人学习！面对国家如此危难之际, 一位高龄老奶奶都能如此大义凛然, 年轻人能无动于衷吗?

（有向这位高龄老奶奶致敬的读者请留言） 郝雪森 2016年9月10日
